Repository pingcap/ticdc, pull requests merged in 2025-09, with the labels that each got.

#1832 ddl: Increase created_at precision of ddl_ts
  downstreamadapter/sink/mysql/sink_test.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, size/S, release-note

#1828 scheduler: Not start any move if the target and the current node are on the same node
  maintainer/barrier_event.go
  maintainer/maintainer_controller_helper.go
  maintainer/operator/operator_move.go
  tests/integration_tests/ddl_with_random_move_table/run.sh
Labels: lgtm, approved, release-note, size/M

#1826 codec: fix incorrect encoding default "null" in Avro protocol
  go.mod
  go.sum
  pkg/sink/codec/avro/arvo.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/confluent_schema_registry.go
  pkg/sink/codec/avro/confluent_schema_registry_test.go
  pkg/sink/codec/avro/glue_schema_registry.go
  pkg/sink/codec/simple/marshaller.go
Labels: lgtm, approved, size/M, release-note-none

#1855 test: fix unstable test `ddl_wait`
  tests/integration_tests/ddl_wait/run.sh
Labels: lgtm, approved, release-note, size/XS

#1900 fix(test): sort actual results in TestApplyDDLJobs for stable comparison
  logservice/schemastore/persist_storage_test.go
Labels: lgtm, approved, size/S, release-note-none

#1898 coordinator: fix test assert and refactor `StopByChangefeedID`
  coordinator/changefeed/backoff.go
  coordinator/changefeed/backoff_test.go
  coordinator/changefeed/changefeed_db.go
  coordinator/changefeed/changefeed_db_test.go
Labels: lgtm, approved, first-time-contributor, release-note, ok-to-test, size/M, contribution

#1588 eventcollector, eventservice: add congestion control mechanism
  downstreamadapter/dispatcher/basic_dispatcher.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/topicmanager/kafka_topic_manager.go
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/subscription_client.go
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/multi_version.go
  logservice/schemastore/schema_store.go
  metrics/grafana/ticdc_new_arch.json
  pkg/common/event/dispatcher_heartbeat.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/common/event/dml_event.go
  pkg/common/event/mounter_test.go
  pkg/common/table_span.go
  pkg/common/types.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/eventservice/metrics_collector.go
  pkg/messaging/message.go
  pkg/metrics/event_service.go
  pkg/metrics/event_store.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_cluster_admin_client.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/sarama_factory.go
  utils/dynstream/memory_control.go
Labels: lgtm, approved, size/XXL, release-note-none

#1924 maintainer: Fix data race
  pkg/scheduler/replica/replication.go
Labels: lgtm, approved, release-note, size/XS

#1925 logpuller: remove unnecessary log
  logservice/logpuller/region_event_handler.go
Labels: lgtm, approved, size/S, release-note

#1810 fix(filter): ensure event filter respects case-sensitive setting
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
Labels: lgtm, approved, size/L, release-note-none

#1883 api: add more verification for changefeed config
  api/status/status.go
  api/v2/changefeed.go
  downstreamadapter/sink/columnselector/column_selector.go
  downstreamadapter/sink/columnselector/column_selector_test.go
  downstreamadapter/sink/eventrouter/event_router.go
  downstreamadapter/sink/kafka/helper.go
  downstreamadapter/sink/pulsar/helper.go
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/validator.go
  maintainer/maintainer_manager.go
  pkg/common/columnselector/column_selector.go
  pkg/common/event/interface.go
  pkg/common/event/row_change.go
  pkg/common/table_info.go
  pkg/common/table_info_helper_test.go
  pkg/errors/error.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/sink/codec/avro/encoder_test.go
  pkg/sink/codec/avro/helper.go
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/canal/canal_json_txn_encoder.go
  pkg/sink/codec/common/utils.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/codec_test.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/open/codec.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
  tests/integration_tests/api_v2/request.go
  tests/integration_tests/api_v2/run.sh
  tests/integration_tests/http_api/run.sh
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/run.sh
  tests/integration_tests/http_api_tls/util/test_case.py
  tests/integration_tests/http_api_tls_with_user_auth/run.sh
  tests/integration_tests/http_api_tls_with_user_auth/util/test_case.py
  tests/utils/checksum_checker/main.go
Labels: lgtm, approved, size/XXL, release-note-none

#1941 scheduler: fix bugs to make scheduler more robust
  maintainer/replica/split_span_checker.go
  maintainer/scheduler/balance_splits.go
  pkg/scheduler/replica/replication.go
  tests/integration_tests/_utils/query_dispatcher_count
  tests/integration_tests/ddl_for_split_tables_random_schedule/conf/changefeed.toml
  tests/integration_tests/ddl_for_split_tables_random_schedule/conf/diff_config.toml
  tests/integration_tests/ddl_for_split_tables_random_schedule/data/pre.sql
  tests/integration_tests/ddl_for_split_tables_random_schedule/run.sh
  tests/integration_tests/ddl_for_split_tables_with_failover/run.sh
  tests/integration_tests/ddl_for_split_tables_with_merge_and_split/run.sh
  tests/integration_tests/ddl_for_split_tables_with_random_merge_and_split/run.sh
  tests/integration_tests/ddl_for_split_tables_with_random_move_table/run.sh
  tests/integration_tests/merge_table/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, release-note, size/L

#1570 eventstore: improve log
  logservice/eventstore/event_store.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/subscription_client.go
  pkg/metrics/event_store.go
Labels: lgtm, approved, release-note, size/M

#1988 maintainer: fix unstable unit test
  maintainer/maintainer_controller_test.go
  maintainer/replica/split_span_checker_test.go
Labels: lgtm, approved, release-note, size/M

#2005 ddl: translate TiDB feature to special comment when spliting queries
  pkg/common/event/util.go
Labels: lgtm, approved, size/S, release-note

#1943 sink(storage): ignore stale dml events
  downstreamadapter/sink/cloudstorage/writer.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
  tests/integration_tests/canal_json_storage_partition_table/conf/diff_config.toml
  tests/integration_tests/canal_json_storage_partition_table/run.sh
Labels: lgtm, approved, release-note, size/L

#2009 cherry pick `cloudstorage: fix a bug causing context cancelled errors and stuck sink`
  pkg/util/external_storage.go
  pkg/util/external_storage_test.go
Labels: lgtm, approved, release-note, size/L

#1503 *: add license
  LICENSE
  third-party-license.txt
Labels: lgtm, approved, release-note, size/L

#2032 sink: fix data race in cloudstorage sink
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/encoding_group.go
Labels: lgtm, approved, size/S, release-note

#1990 ddl: fix corner case for batch syncpoint event
  downstreamadapter/dispatcher/basic_dispatcher.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/sink/mysql/sink_test.go
  maintainer/barrier_event.go
  maintainer/barrier_test.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, release-note, size/XXL

#2121 logpuller: fix a data race in priority queue
  logservice/logpuller/priority_queue.go
  logservice/logpuller/priority_queue_test.go
Labels: lgtm, approved, size/M, release-note-none

#2080 kafka-consumer: Fix unstable test `cdc` in kafka
  cmd/kafka-consumer/writer.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/sql_builder.go
  tests/integration_tests/_utils/run_kafka_consumer
Labels: lgtm, approved, release-note, size/L, subject/replication-interruption

#2140 error: Unify the pkg error package and Add shouldFailChangefeed check for maintainer error
  api/middleware/authenticate_middleware.go
  api/v2/changefeed.go
  coordinator/coordinator.go
  downstreamadapter/dispatcher/event_dispatcher.go
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
  downstreamadapter/eventcollector/event_collector.go
  maintainer/maintainer_controller_helper.go
  pkg/apperror/errors.go
  pkg/common/event/ddl_event_test.go
  pkg/errors/error.go
  pkg/errors/error_test.go
  pkg/errors/helper.go
  pkg/errors/utils.go
  pkg/etcd/client.go
  pkg/eventservice/event_broker.go
  pkg/messaging/local_target.go
  pkg/messaging/message_center.go
  pkg/messaging/remote_target.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_for_syncpoint.go
  utils/dynstream/parallel_dynamic_stream.go
Labels: lgtm, approved, release-note, size/XXL

#2159 eventService: fix an unstable unit test
  pkg/eventservice/event_service_test.go
Labels: lgtm, approved, size/XS, release-note-none

#2141 mysql: enter safemode and retry when encounter `Duplicate entry` error
  pkg/eventservice/event_service_test.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_dml_test.go
  pkg/sink/mysql/mysql_writer_test.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/mysql/sql_builder_benchmark_test.go
  pkg/sink/mysql/sql_builder_test.go
  tests/integration_tests/mysql_sink_retry/conf/diff_config.toml
  tests/integration_tests/mysql_sink_retry/data/down_data.sql
  tests/integration_tests/mysql_sink_retry/data/up_data.sql
  tests/integration_tests/mysql_sink_retry/data/up_ddl.sql
  tests/integration_tests/mysql_sink_retry/run.sh
Labels: lgtm, approved, size/XXL, release-note-none

#2170 eventstore: fix cannot find subStat panic
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
Labels: lgtm, approved, size/XL, release-note

#2166 logpuller: fix a data race
  logservice/logpuller/region_req_cache.go
  logservice/logpuller/region_req_cache_test.go
Labels: lgtm, approved, size/S, release-note-none

#2188 syncpoint: use a better name to make code more readable
  downstreamadapter/dispatcher/basic_dispatcher.go
  downstreamadapter/dispatcher/basic_dispatcher_info.go
  downstreamadapter/dispatcher/event_dispatcher.go
  downstreamadapter/dispatcher/redo_dispatcher.go
  downstreamadapter/dispatcher/redo_dispatcher_test.go
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  downstreamadapter/dispatchermanager/dispatcher_manager_redo.go
  downstreamadapter/dispatchermanager/task.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/event_collector_test.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/syncpoint/sync_point.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
Labels: lgtm, approved, release-note, size/L

#2193 eventStore: fix a panic
  coordinator/changefeed/etcd_backend.go
  logservice/eventstore/event_store.go
Labels: lgtm, approved, size/S, release-note-none

#2199 maintainer: fix data race
  maintainer/barrier_event_test.go
  maintainer/replica/default_span_split_checker.go
  maintainer/span/span_controller.go
Labels: lgtm, approved, size/S, release-note

#2198 Improve changefeed keyspace management by refactoring etcd key extraction and registering all active keyspaces.
  coordinator/changefeed/etcd_backend.go
  coordinator/changefeed/etcd_backend_test.go
  coordinator/controller.go
  coordinator/coordinator_test.go
  logservice/schemastore/schema_store.go
  pkg/common/event/mounter.go
  pkg/common/types.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service_test.go
  pkg/eventservice/test_helper.go
Labels: lgtm, approved, size/XL, release-note-none

#2146 *: add more tools to check
  Makefile
  logservice/schemastore/types_gen.go
  pkg/common/event/row_change.go
  pkg/common/kv_entry.go
  pkg/redo/writer/file/file.go
  pkg/redo/writer/file/file_mock.go
  tools/check/go.mod
  tools/check/go.sum
Labels: lgtm, approved, release-note, size/L

#2215 metrics: update grafana for ddl
  maintainer/barrier_event.go
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/L

#2040 feat(*): Implement `force-replicate` and `ignore_ineligible_table` in the filter and refactor eligibility checks
  api/v2/changefeed.go
  cmd/filter-helper/main.go
  downstreamadapter/dispatcher/basic_dispatcher.go
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/table_info.go
  pkg/diff/diff.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/mysql/sql_builder_benchmark_test.go
  pkg/sink/mysql/sql_builder_test.go
  tests/integration_tests/cdc/dailytest/case.go
  tests/integration_tests/http_api_tls/util/test_case.py
  tests/integration_tests/http_api_tls_with_user_auth/util/test_case.py
Labels: lgtm, approved, size/XL, release-note-none

#2244 eventborker: update wrong received resolved ts metrics
  logservice/schemastore/schema_store.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/metrics_collector.go
  pkg/eventservice/test_helper.go
Labels: lgtm, approved, release-note, size/M

#2222 DS: fix a data race that may cause PANIC
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  utils/dynstream/parallel_dynamic_stream.go
  utils/dynstream/parallel_dynamic_stream_test.go
  utils/dynstream/stream.go
  utils/dynstream/stream_bench_test.go
  utils/dynstream/stream_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1929 metrics: fix more metrics metrics: fix more metrics | tikv=release-8.5 | tidb=release-8.5 | pd=release-8.5
  cmd/cdc/server/server.go
  coordinator/changefeed/changefeed.go
  coordinator/changefeed/changefeed_db.go
  coordinator/changefeed/etcd_backend.go
  coordinator/controller.go
  coordinator/coordinator.go
  coordinator/operator/operator_controller.go
  logservice/coordinator/coordinator.go
  maintainer/maintainer.go
  maintainer/maintainer_manager.go
  metrics/grafana/ticdc_new_arch.json
  pkg/metrics/changefeed.go
  pkg/metrics/coordinator.go
  pkg/metrics/dispatcher.go
  pkg/metrics/ds.go
  pkg/metrics/event_service.go
  pkg/metrics/event_store.go
  pkg/metrics/init.go
  pkg/metrics/log_puller.go
  pkg/metrics/maintainer.go
  pkg/metrics/messaging.go
  pkg/metrics/puller.go
  pkg/metrics/scheduler.go
  pkg/metrics/schema_store.go
  pkg/metrics/server.go
  pkg/metrics/sink.go
  pkg/scheduler/replica/replication.go
  pkg/scheduler/replica/replication_group.go
  pkg/sink/kafka/metrics.go
Labels: lgtm, approved, size/XXL, release-note-none

#2290 metrics: Added checkpointTs lag reported by the coordinator
  coordinator/controller.go
  metrics/grafana/ticdc_new_arch.json
  pkg/config/changefeed.go
  pkg/metrics/changefeed.go
Labels: lgtm, approved, size/XL, release-note

#2294 Register keyspace when it was not found in the schema cache
  cmd/cdc/cli/cli_changefeed_create.go
  cmd/cdc/cli/cli_changefeed_pause.go
  logservice/schemastore/schema_store.go
  logservice/txnutil/lock_resolver.go
  maintainer/testutil/test_util.go
  pkg/common/span_op.go
  pkg/errors/error.go
  pkg/eventservice/event_broker.go
  pkg/keyspace/keyspace_manager.go
  pkg/pdutil/api_client.go
Labels: lgtm, approved, release-note, size/L

#2285 fix(ddl): use correct table info for exchange partition ddl
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/persist_storage_test_utils.go
  pkg/common/table_info.go
Labels: lgtm, approved, size/L, release-note-none

#2296 mysql: group events by tableInfo updateTs
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/mounter.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_dml_test.go
Labels: lgtm, approved, size/XL, release-note-none

#2328 *: remove debug log
  pkg/common/event/mounter.go
Labels: lgtm, approved, size/S

#2147 fix(dispatcher): ensure dispatcher receives correct TableInfo for multi-table DDLs
  downstreamadapter/dispatcher/basic_dispatcher.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/ddl_event.go
Labels: lgtm, approved, size/L, release-note-none

#2316 tests: Add integration test to validate changefeed state persistence across CDC server restarts, including paused and active states.
  tests/integration_tests/restart_changefeed/conf/diff_config.toml
  tests/integration_tests/restart_changefeed/run.sh
Labels: lgtm, approved, size/L, release-note-none

#2291 logs: simplify logs and remove some useless log fields
  logservice/logpuller/subscription_client.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/schema_store.go
  logservice/schemastore/unsorted_cache.go
  logservice/schemastore/utils.go
  logservice/txnutil/lock_resolver.go
  pkg/eventservice/event_broker.go
  pkg/txnutil/gc/gc_manager.go
Labels: lgtm, approved, size/L, release-note-none

#2334 metrics: removes the metric correctly about redo
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  downstreamadapter/eventcollector/event_collector.go
Labels: lgtm, approved, size/S, release-note

#2232 Add a script to download integration test binaries for macOS to simplify the setup of integration test environments.
  tests/scripts/download-integration-test-binaries-macos.sh
Labels: lgtm, approved, size/L, release-note-none

#2273 metrics: update changefeed resolved ts metrics by log coordinator
  logservice/coordinator/coordinator.go
  logservice/coordinator/coordinator_test.go
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
  logservice/logservicepb/logservice.pb.go
  logservice/logservicepb/logservice.proto
  maintainer/maintainer.go
  metrics/grafana/ticdc_new_arch.json
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_service_test.go
  pkg/messaging/message.go
  pkg/metrics/init.go
  pkg/metrics/log_coordinator.go
  pkg/pdutil/clock.go
Labels: lgtm, approved, release-note, size/XXL

#2354 chore(*): upgrade tiflow dependency
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
Labels: lgtm, approved, size/XXL, release-note-none

#2367 eventstore: fix data race
  logservice/eventstore/event_store_test.go
Labels: lgtm, approved, size/S, release-note

#2348 scheduler: reduce query region count frequency
  maintainer/replica/default_span_split_checker.go
  maintainer/replica/default_span_split_checker_test.go
  maintainer/replica/split_span_checker.go
  maintainer/replica/split_span_checker_test.go
Labels: lgtm, approved, size/S, release-note

#2368 operator: reduce print frequency of meanless log
  maintainer/operator/helper.go
  maintainer/operator/operator_controller.go
Labels: lgtm, approved, release-note, size/M

#2383 feat(*): enable newarch by default
  cmd/cdc/server/server.go
  pkg/config/server.go
Labels: lgtm, approved, size/M, release-note-none

#2382 tests: fix unstable integration test `ddl_wait`
  tests/integration_tests/ddl_wait/run.sh
  tests/integration_tests/ddl_wait/test.go
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/S, release-note-none

#2400 operatorController: fix panic
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  maintainer/operator/operator_controller.go
Labels: lgtm, approved, release-note, size/XS

#2297 ddl: ignore duplicate tableID in rename tables
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/eventservice/event_broker.go
  tests/integration_tests/common_1/conf/diff_config.toml
  tests/integration_tests/common_1/data/test_finish.sql
Labels: lgtm, approved, size/L, release-note-none

#2427 matcher: revert report error if matcher cannot found prewrite in the next-gen mode
  logservice/logpuller/region_event_handler.go
Labels: lgtm, approved, size/M, release-note-none
