Repository pingcap/ticdc, pull requests merged in 2025-04, with the labels that each got.

#1193 codec: add open protocol decoder
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/test_helper.go
  pkg/sink/codec/open/codec.go
  pkg/sink/codec/open/codec_test.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/open/message.go
Labels: lgtm, approved, size/XXL, release-note-none

#1203 mysql: extract col value meet error then panic immediately
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/sink/blackhole.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/cloudstorage_test.go
  downstreamadapter/sink/conflictdetector/conflict_detector.go
  downstreamadapter/sink/conflictdetector/helper.go
  downstreamadapter/sink/helper/eventrouter/partition/columns.go
  downstreamadapter/sink/helper/eventrouter/partition/index_value.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/sink/kafka_sink_test.go
  downstreamadapter/sink/mysql_sink.go
  downstreamadapter/sink/pulsar_sink.go
  downstreamadapter/sink/pulsar_sink_test.go
  downstreamadapter/sink/sink.go
  pkg/common/event/mounter_test.go
  pkg/common/event/redo.go
  pkg/common/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/mysql/sql_builder_benchmark_test.go
  pkg/sink/mysql/sql_builder_test.go
Labels: lgtm, approved, size/XL, release-note-none

#1185 sink: remove ColumnFlagType
  downstreamadapter/sink/conflictdetector/helper.go
  downstreamadapter/sink/helper/eventrouter/partition/index_value.go
  pkg/common/column.go
  pkg/common/event/row_change.go
  pkg/common/flag.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/common/table_info_helper_test.go
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/helper.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/open/codec.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/open/message.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/message.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/sink/mysql/sql_builder.go
Labels: lgtm, approved, size/XXL, release-note-none

#1200 codec: add simple protocol decoder
  pkg/common/event/util.go
  pkg/common/table_info_helper.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/utils.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller_bench_test.go
  pkg/sink/codec/simple/message.go
Labels: lgtm, approved, size/XXL, release-note-none

#1168 ci: add ci for kafka, pulsar and storage integration tests
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/L, release-note-none

#1214 mysql: rename some struct to make it less verbose
  downstreamadapter/sink/conflictdetector/helper.go
  downstreamadapter/sink/mysql_sink.go
  downstreamadapter/worker/mysql_worker.go
  pkg/common/event/dml_event.go
  pkg/common/event/redo.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_for_syncpoint.go
  pkg/sink/mysql/mysql_writer_test.go
  pkg/sink/mysql/sql_builder.go
Labels: lgtm, approved, size/L, release-note-none

#1208 Upgrade go-mysql to v1.12.0
  go.mod
  go.sum
Labels: lgtm, approved, first-time-contributor, size/S, release-note-none

#1202 mysql: remove the mysql worker abstraction and adjust the code
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/sink/blackhole.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/cloudstorage_test.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/sink/kafka_sink_test.go
  downstreamadapter/sink/mysql/causality/conflict_detector.go
  downstreamadapter/sink/mysql/causality/helper.go
  downstreamadapter/sink/mysql/causality/node.go
  downstreamadapter/sink/mysql/causality/slot.go
  downstreamadapter/sink/mysql/causality/txn_cache.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/mysql_sink.go
  downstreamadapter/sink/pulsar_sink.go
  downstreamadapter/sink/pulsar_sink_test.go
  downstreamadapter/sink/sink.go
  downstreamadapter/worker/mysql_worker.go
  downstreamadapter/worker/writer/worker.go
  pkg/common/table_info_helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1213 Decouple the scheduler logic from maintainer and coordinator
  coordinator/controller.go
  coordinator/scheduler/balance.go
  coordinator/scheduler/basic.go
  maintainer/maintainer_controller.go
  maintainer/scheduler.go
  maintainer/scheduler/balance.go
  maintainer/scheduler/basic.go
  maintainer/scheduler/split.go
  pkg/scheduler/balance.go
  pkg/scheduler/basic.go
Labels: lgtm, approved, release-note, size/XXL

#1042 sink: modify index column of table info
  downstreamadapter/sink/mysql/causality/helper.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/common/table_info_helper_test.go
  pkg/sink/mysql/mysql_writer_helper.go
Labels: lgtm, approved, size/L, release-note-none

#1201 messaging: refactor messgeCenter
  coordinator/coordinator_test.go
  downstreamadapter/downstream_performance_test.go
  maintainer/barrier_event_test.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  pkg/apperror/errors.go
  pkg/common/event/mounter_test.go
  pkg/common/event/redo_gen_compatibility_test.go
  pkg/config/messging.go
  pkg/messaging/local_target.go
  pkg/messaging/message_center.go
  pkg/messaging/message_center_integration_test.go
  pkg/messaging/proto/message.pb.go
  pkg/messaging/proto/message.proto
  pkg/messaging/proto/message_grpc.pb.go
  pkg/messaging/remote_target.go
  pkg/messaging/stream.go
  pkg/messaging/target.go
  pkg/messaging/target_test.go
  pkg/metrics/messaging.go
  server/module_grpc.go
  server/server.go
Labels: lgtm, approved, size/XXL, release-note-none

#1194 codec: add Avro protocol
  go.mod
  pkg/common/event/row_change.go
  pkg/errors/error.go
  pkg/sink/codec/avro/arvo.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/confluent_schema_registry_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/encoder.go
  pkg/sink/codec/avro/encoder_test.go
  pkg/sink/codec/avro/glue_schema_registry_test.go
  pkg/sink/codec/avro/helper.go
  pkg/sink/codec/avro/helper_test.go
  pkg/sink/codec/avro/mock_schema_registry.go
  pkg/sink/codec/avro/schema_manager.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/helper_test.go
  pkg/sink/codec/encoder_builder.go
  tests/integration_tests/_utils/run_sql
  tests/integration_tests/_utils/run_sql_ignore_error
  tests/integration_tests/avro_basic/run.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XXL, release-note-none

#1221 mq: remove the mq worker and producer interface
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/sink/blackhole.go
  downstreamadapter/sink/blackhole_test.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/cloudstorage_test.go
  downstreamadapter/sink/eventrouter/event_router.go
  downstreamadapter/sink/eventrouter/event_router_test.go
  downstreamadapter/sink/eventrouter/partition/columns.go
  downstreamadapter/sink/eventrouter/partition/generator.go
  downstreamadapter/sink/eventrouter/partition/index_value.go
  downstreamadapter/sink/eventrouter/partition/key.go
  downstreamadapter/sink/eventrouter/partition/table.go
  downstreamadapter/sink/eventrouter/partition/ts.go
  downstreamadapter/sink/eventrouter/topic/expression.go
  downstreamadapter/sink/eventrouter/topic/topic.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/sink/kafka/helper.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/kafka/sink_test.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/pulsar/ddl_producer.go
  downstreamadapter/sink/pulsar/ddl_producer_test.go
  downstreamadapter/sink/pulsar/dml_producer.go
  downstreamadapter/sink/pulsar/dml_producer_test.go
  downstreamadapter/sink/pulsar/helper.go
  downstreamadapter/sink/pulsar/mock_producer.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/pulsar/sink_test.go
  downstreamadapter/sink/pulsar_sink.go
  downstreamadapter/sink/sink.go
  downstreamadapter/sink/topicmanager/kafka_topic_manager.go
  downstreamadapter/sink/topicmanager/kafka_topic_manager_test.go
  downstreamadapter/sink/topicmanager/pulsar_topic_manager.go
  downstreamadapter/sink/topicmanager/pulsar_topic_manager_mock.go
  downstreamadapter/sink/topicmanager/pulsar_topic_manager_test.go
  downstreamadapter/sink/topicmanager/topic_manager.go
  downstreamadapter/worker/helper.go
  downstreamadapter/worker/mq_ddl_worker.go
  downstreamadapter/worker/mq_ddl_worker_test.go
  downstreamadapter/worker/mq_dml_worker.go
  downstreamadapter/worker/mq_dml_worker_test.go
  downstreamadapter/worker/producer/kafka_ddl_producer.go
  downstreamadapter/worker/producer/kafka_ddl_producer_test.go
  downstreamadapter/worker/producer/kafka_dml_producer.go
  downstreamadapter/worker/producer/kafka_dml_producer_test.go
  downstreamadapter/worker/producer/kafka_mock_producer.go
  downstreamadapter/worker/producer/producer.go
  pkg/errors/error.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/pulsar/factory.go
Labels: lgtm, approved, size/XXL, release-note-none

#1225 messaging: fix a data race in message target
  pkg/messaging/remote_target.go
Labels: lgtm, approved, size/S, release-note-none

#1228 codec: fix the open protocol flag
  pkg/sink/codec/open/codec.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/open/message.go
Labels: lgtm, approved, size/XL, release-note-none

#1237 dependencies: bump sarama to fix the kafka cluste stuck and data race panic problem
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note-none

#1233 codec: add csv protocol decoder
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_decoder_test.go
  pkg/sink/codec/csv/csv_message.go
Labels: lgtm, approved, size/XL, release-note-none

#1234 codec: add debezium protocol decoder
  pkg/errors/error.go
  pkg/sink/codec/debezium/decode.go
Labels: lgtm, approved, size/XL, release-note-none

#1238 cloudstorage: fix a bug that may cause changefeed getting stuck
  cmd/storage-consumer/main.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/worker/cloudstorage_ddl_worker_test.go
  downstreamadapter/worker/cloudstorage_dml_worker_test.go
  downstreamadapter/worker/writer/writer_test.go
  pkg/redo/config.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/codec/open/encoder_test.go
  pkg/util/external_storage.go
  pkg/util/external_storage_test.go
  pkg/util/tz_test.go
Labels: lgtm, approved, size/XL, release-note

#1210 sink: send bootstrap event when changefeed with simple protocol start
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  pkg/common/table_info.go
  pkg/sink/util/helper.go
  tests/integration_tests/kafka_simple_basic/run.sh
Labels: lgtm, approved, size/L, release-note-none

#1245 *: support row checksum
  api/v2/model.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/pulsar/sink.go
  eventpb/event.pb.go
  eventpb/event.proto
  logservice/eventstore/event_store.go
  pkg/common/event/checksum.go
  pkg/common/event/chunk.go
  pkg/common/event/dml_event.go
  pkg/common/event/mounter.go
  pkg/common/event/row_change.go
  pkg/common/event/util.go
  pkg/config/replica_config.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/integrity/checksum.go
  pkg/integrity/integrity.go
  pkg/messaging/message.go
  pkg/sink/codec/avro/arvo.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/utils.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/message.go
Labels: lgtm, approved, size/XXL, release-note-none

#1235 mysql: wait the asynchronous ddl to synchronize
  pkg/errors/error.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_test.go
  tests/integration_tests/ddl_wait/conf/diff_config.toml
  tests/integration_tests/ddl_wait/run.sh
  tests/integration_tests/ddl_wait/test.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XL, release-note-none

#1222 cloudstorage: move cloud storage sink to the specified package
  Makefile
  downstreamadapter/sink/blackhole/sink.go
  downstreamadapter/sink/blackhole/sink_test.go
  downstreamadapter/sink/blackhole_test.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/cloudstorage/defragmenter.go
  downstreamadapter/sink/cloudstorage/defragmenter_test.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/dml_writers_test.go
  downstreamadapter/sink/cloudstorage/encoding_group.go
  downstreamadapter/sink/cloudstorage/sink.go
  downstreamadapter/sink/cloudstorage/sink_test.go
  downstreamadapter/sink/cloudstorage/writer.go
  downstreamadapter/sink/cloudstorage/writer_test.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/sink.go
  downstreamadapter/worker/cloudstorage_ddl_worker_test.go
  downstreamadapter/worker/cloudstorage_dml_worker.go
  downstreamadapter/worker/writer/worker.go
  downstreamadapter/worker/writer/worker_test.go
  pkg/sink/codec/canal/canal_json_txn_encoder.go
  pkg/sink/codec/encoder_builder.go
  pkg/sink/mysql/mysql_writer.go
Labels: lgtm, approved, size/XXL, release-note-none

#1240 http: fix the api capture list output does not match the old architecture
  api/v2/model.go
  downstreamadapter/sink/mysql/causality/conflict_detector.go
  downstreamadapter/sink/mysql/sink.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/cli_tls_with_auth/run.sh
  tests/integration_tests/cli_with_auth/run.sh
  tests/integration_tests/http_api/run.sh
Labels: lgtm, approved, size/M, release-note-none

#1219 maintainer: New scheduling algorithm for basic schedule
  api/v2/model.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/helper.go
  heartbeatpb/heartbeat.pb.go
  heartbeatpb/heartbeat.proto
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  maintainer/replica/replication_span.go
  maintainer/scheduler.go
  maintainer/scheduler/balance.go
  maintainer/scheduler/basic.go
  maintainer/scheduler/split.go
  maintainer/split/region_count_splitter.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/splitter.go
  pkg/config/replica_config.go
  pkg/config/scheduler_config.go
  pkg/scheduler/replica/replication.go
  pkg/scheduler/replica/replication_group.go
  pkg/sink/mysql/mysql_writer_dml.go
  tests/integration_tests/_utils/check_sync_diff
  tests/integration_tests/batch_add_table/run.sh
  tests/integration_tests/default_value/run.sh
Labels: lgtm, approved, release-note, size/XXL

#1263 split: add unit test for region count splitter
  downstreamadapter/sink/mysql/sink.go
  maintainer/maintainer_controller.go
  maintainer/split/region_count_splitter.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/splitter.go
Labels: lgtm, approved, release-note, size/L

#1247 CI: add OWNERS files with sig-critical-approvers aliases
  OWNERS_ALIASES
  pkg/config/OWNERS
Labels: lgtm, approved, first-time-contributor, size/S, release-note-none

#1264 maintainer: adjust some ut in maintainer
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  maintainer/scheduler/balance.go
  maintainer/scheduler/basic.go
Labels: lgtm, approved, release-note, size/M

#1260 *: fix data race in dynamic stream
  server/server.go
Labels: lgtm, approved, size/M, release-note-none

#1268 *: fix incorrect row checksum
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/pulsar/sink.go
  pkg/common/event/dml_event.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_txn_decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/utils.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/debezium/decode.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/simple/decoder.go
Labels: lgtm, approved, size/L, release-note-none

#1273 redo: add redo cmd
  Makefile
  cmd/cdc/main.go
  cmd/cdc/redo/apply.go
  cmd/cdc/redo/apply_test.go
  cmd/cdc/redo/meta.go
  cmd/cdc/redo/redo.go
  go.mod
  pkg/applier/main_test.go
  pkg/applier/redo.go
  pkg/applier/redo_test.go
  pkg/errors/error.go
  pkg/fsutil/preallocate_linux.go
  pkg/util/memory.go
Labels: lgtm, approved, size/XXL, release-note-none

#1276 *: Eliminate tiflow dependencies about sink
  downstreamadapter/sink/cloudstorage/writer.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/metrics/cloudstorage.go
  downstreamadapter/sink/metrics/mq.go
  downstreamadapter/sink/pulsar/ddl_producer.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/topicmanager/pulsar_topic_manager_test.go
  pkg/common/event/row_change.go
  pkg/errors/error.go
  pkg/errors/helper.go
  pkg/eventservice/event_service_test.go
  pkg/fsutil/disk_info_freebsd.go
  pkg/fsutil/disk_info_generic.go
  pkg/fsutil/file_allocator_test.go
  pkg/orchestrator/reactor_state.go
  pkg/retry/error_retry.go
  pkg/retry/main_test.go
  pkg/retry/retry_with_opt.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/path_key.go
  pkg/sink/codec/avro/helper_test.go
  pkg/sink/codec/bootstraper.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_txn_encoder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/helper_test.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_encoder.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/debezium/helper.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/marshaller_bench_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/factory.go
  pkg/sink/sqlmodel/multi_row.go
  pkg/sink/sqlmodel/row_change.go
  pkg/sink/util/helper.go
  pkg/util/external_storage.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XL, release-note-none

#1278 *: Eliminate tiflow dependencies about pkg and server
  downstreamadapter/sink/eventrouter/partition/columns.go
  downstreamadapter/sink/eventrouter/partition/index_value.go
  downstreamadapter/sink/mysql/causality/helper.go
  pkg/api/internal/rest/request.go
  pkg/apperror/util.go
  pkg/applier/main_test.go
  pkg/common/column.go
  pkg/common/columnselector/column_selector_test.go
  pkg/common/event/util.go
  pkg/common/span_hash_map.go
  pkg/errors/error.go
  pkg/etcd/client.go
  pkg/etcd/etcd.go
  pkg/etcd/mock/etcd.go
  pkg/eventservice/main_test.go
  pkg/fsutil/file_allocator.go
  pkg/fsutil/filelock.go
  pkg/fsutil/fileutil.go
  pkg/fsutil/main_test.go
  pkg/httputil/main_test.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  pkg/pdutil/api_client.go
  pkg/pdutil/api_client_test.go
  pkg/pdutil/main_test.go
  pkg/pdutil/utils.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/spanz/hash_map.go
  pkg/spanz/span.go
  pkg/util/comparison.go
  pkg/util/comparison_test.go
  pkg/util/seahash/LICENSE.md
  pkg/util/seahash/seahash.go
  pkg/util/seahash/seahash_test.go
  pkg/version/check.go
  redo/common/main_test.go
  redo/manager.go
  redo/reader/main_test.go
  redo/writer/file/main_test.go
  redo/writer/memory/main_test.go
  server/module_election.go
  server/module_http.go
  server/server_prepare.go
Labels: lgtm, approved, size/XXL, release-note-none

#1279 Support set go limit to avoid oom
  go.mod
  pkg/config/server.go
  server/server_prepare.go
Labels: lgtm, approved, release-note, size/M

#1283 api: fix the client return no owner
  api/v2/capture.go
  api/v2/model.go
  cmd/cdc/cli/cli_capture_list.go
  tests/integration_tests/cli_tls_with_auth/run.sh
  tests/integration_tests/cli_with_auth/run.sh
Labels: lgtm, approved, size/M, release-note-none

#1288 sink: simplify the event router method interface
  downstreamadapter/sink/eventrouter/event_router.go
  downstreamadapter/sink/eventrouter/event_router_test.go
  downstreamadapter/sink/eventrouter/partition/generator.go
  downstreamadapter/sink/eventrouter/topic/expression.go
  downstreamadapter/sink/eventrouter/topic/topic.go
  downstreamadapter/sink/kafka/helper.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/pulsar/helper.go
  downstreamadapter/sink/pulsar/sink.go
Labels: lgtm, approved, size/L, release-note-none

#1262 eventService, dispatcher: add heartbeat
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  eventpb/event.pb.go
  eventpb/event.proto
  logservice/eventstore/event_store.go
  pkg/common/event/dispatcher_heartbeat.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_service.go
  pkg/messaging/message.go
Labels: lgtm, approved, size/XXL, release-note-none

#1281 eventService: fix a bug that may cause event seq error
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/helper.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  utils/dynstream/stream.go
Labels: lgtm, approved, release-note, size/L

#1285 eventBroker: limit txn number in a scan task
  downstreamadapter/eventcollector/helper.go
  logservice/eventstore/pebble.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_service_test.go
  pkg/sink/mysql/mysql_writer_dml.go
  utils/dynstream/stream.go
Labels: lgtm, approved, release-note, size/M

#1290 sink: move some helper method to the caller package
  downstreamadapter/sink/cloudstorage/defragmenter_test.go
  downstreamadapter/sink/cloudstorage/sink.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/sink/kafka/helper.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/pulsar/helper.go
  downstreamadapter/sink/pulsar/sink.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  pkg/common/columnselector/column_selector.go
  pkg/common/columnselector/column_selector_test.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/util/helper.go
Labels: lgtm, approved, size/L, release-note-none
