Repository pingcap/ticdc, pull requests merged in 2025-02, with the labels that each got.

#964 mysql: fix and add test for async ddl `add index`
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, release-note, size/L

#960 Fix DDL split events
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/utils.go
  pkg/common/event/ddl_event.go
  pkg/common/event/ddl_event_test.go
  pkg/common/event/util.go
Labels: lgtm, approved, release-note, size/L

#966 feat: Migrate spanz module from tiflow
  cmd/kafka-consumer/writer.go
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  heartbeatpb/table_span.go
  logservice/coordinator/coordinator.go
  logservice/coordinator/coordinator_test.go
  logservice/logpuller/region_event_handler_test.go
  logservice/logpuller/regionlock/region_range_lock_test.go
  logservice/logpuller/subscription_client.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager_test.go
  maintainer/range_checker/table_span_range_checker.go
  maintainer/range_checker/table_span_range_checker_test.go
  maintainer/replica/replication_db_test.go
  maintainer/replica/replication_span.go
  maintainer/scheduler.go
  maintainer/split/region_count_splitter_test.go
  pkg/common/event/mounter.go
  pkg/pdutil/api_client.go
  pkg/pdutil/api_client_test.go
  pkg/spanz/btree_map.go
  pkg/spanz/btree_map_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
  pkg/spanz/hash_map.go
  pkg/spanz/hash_map_test.go
  pkg/spanz/map_bench_test.go
  pkg/spanz/set.go
  pkg/spanz/set_test.go
  pkg/spanz/span.go
  pkg/spanz/span_test.go
  pkg/spanz/sync_map.go
Labels: lgtm, approved, size/XXL, release-note-none

#970 *: fix panic when server prepare
  server/server_prepare.go
Labels: lgtm, approved, release-note, size/XS

#973 puller: fix remove path
  logservice/logpuller/subscription_client.go
Labels: lgtm, approved, release-note, size/XS

#972 *: update binary download link in readme
  README.md
Labels: lgtm, approved, release-note, size/XS

#974 ddl: add multiple table infos
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/ddl_event.go
Labels: lgtm, approved, release-note, size/M

#975 Add test for resume with overwrite checkpointTs
  .github/workflows/integration_test_mysql.yaml
  tests/integration_tests/overwrite_resume_with_syncpoint/conf/changefeed.toml
  tests/integration_tests/overwrite_resume_with_syncpoint/run.sh
Labels: lgtm, approved, release-note, size/M

#976 schemastore: ignore unsupported ddl types
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/persist_storage_test_utils.go
Labels: lgtm, approved, release-note, size/M

#978 coordinator: improve the log format and code struct
  coordinator/changefeed/backoff.go
  coordinator/changefeed/changefeed.go
  coordinator/changefeed/changefeed_db.go
  coordinator/changefeed/changefeed_db_test.go
  coordinator/controller.go
  coordinator/coordinator.go
  coordinator/operator/operator_controller.go
  coordinator/operator/operator_stop.go
  downstreamadapter/dispatcher/dispatcher.go
  logservice/eventstore/event_store.go
  maintainer/maintainer.go
  maintainer/maintainer_manager.go
  maintainer/operator/operator_controller.go
  pkg/common/format.go
  pkg/eventservice/event_broker.go
  pkg/node/node.go
  server/module_election.go
  tests/integration_tests/changefeed_dup_error_restart/run.sh
Labels: lgtm, approved, size/XXL, release-note-none

#979 *: small refactor ddl event
  .github/workflows/integration_test_mysql.yaml
  downstreamadapter/sink/helper/eventrouter/event_router.go
  downstreamadapter/sink/helper/eventrouter/event_router_test.go
  logservice/schemastore/disk_format.go
  logservice/schemastore/multi_version_test.go
  logservice/schemastore/multi_version_test_utils.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/types.go
  logservice/schemastore/types_gen.go
  pkg/common/event/ddl_event.go
  pkg/sink/codec/avro/glue_schema_registry.go
  pkg/sink/codec/canal/encoder.go
Labels: lgtm, approved, release-note, size/XXL

#927 sink: support cloud storage sink
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/cloudstorage_test.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/sink/sink.go
  downstreamadapter/worker/cloudstorage_ddl_worker.go
  downstreamadapter/worker/cloudstorage_dml_worker.go
  downstreamadapter/worker/writer/defragmenter.go
  downstreamadapter/worker/writer/worker.go
  downstreamadapter/worker/writer/writer.go
  go.mod
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/ddl_event.go
  pkg/common/types.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_key.go
  pkg/sink/cloudstorage/path_key_test.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
  pkg/sink/codec/canal/encoder.go
  pkg/sink/codec/common/encoder.go
  pkg/sink/codec/csv/csv_encoder.go
  pkg/sink/codec/csv/csv_encoder_test.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/encoder_builder.go
Labels: lgtm, approved, release-note, size/XXL

#990 api: make all api/v2 compatible with old TiCDC.
  api/v2/api.go
  api/v2/changefeed.go
  api/v2/model.go
  api/v2/processor.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/helper.go
  maintainer/maintainer.go
  pkg/config/changefeed.go
  pkg/eventservice/event_service.go
  pkg/messaging/message.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/cli_tls_with_auth/run.sh
  tests/integration_tests/cli_with_auth/run.sh
  tests/integration_tests/http_api/run.sh
Labels: lgtm, approved, size/L, release-note-none

#986 Support batch dml in mysql sink
  downstreamadapter/sink/mysql_sink_test.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/sqlmodel/multi_row.go
  pkg/sink/sqlmodel/row_change.go
  pkg/sink/sqlmodel/utils.go
  pkg/sink/sqlmodel/where_handle.go
  tests/integration_tests/cdc/cdc.go
  tests/integration_tests/cdc/dailytest/case.go
Labels: lgtm, approved, release-note, size/XXL

#993 DS: refactor memory control module
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
  downstreamadapter/eventcollector/event_collector.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/parallel_dynamic_stream_test.go
Labels: lgtm, approved, size/XL, release-note-none

#995 api: add HTTP API v1
  api/http.go
  api/v1/api.go
  api/v2/api.go
  api/v2/capture.go
  api/v2/changefeed.go
  api/v2/coordinator.go
  api/v2/health.go
  api/v2/helper.go
  api/v2/log.go
  api/v2/processor.go
  api/v2/status.go
Labels: lgtm, approved, size/XL, release-note-none

#984 puller: small refactor
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/region_request_worker.go
Labels: lgtm, approved, size/S, release-note

#992 split-table: make split-table more useful
  downstreamadapter/dispatcher/table_progress.go
  maintainer/replica/checker.go
  maintainer/split/region_count_splitter.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/write_bytes_splitter.go
  maintainer/split/write_bytes_splitter_test.go
Labels: lgtm, approved, release-note, size/M

#997 schemastore: fix panic after recover table
  logservice/schemastore/multi_version.go
  logservice/schemastore/multi_version_test.go
  logservice/schemastore/multi_version_test_utils.go
  logservice/schemastore/persist_storage.go
Labels: lgtm, approved, release-note, size/M

#999 schemastore: fix load full table info failed
  .github/workflows/integration_test_mysql.yaml
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_ddl_handlers.go
Labels: lgtm, approved, release-note, size/L

#996 DS, mysql: enhance dry run mode and refactor DS memory control
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/eventcollector/event_collector.go
  metrics/grafana/ticdc_new_arch.json
  pkg/common/types.go
  pkg/eventservice/event_broker.go
  pkg/metrics/ds.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_ddl.go
  tests/integration_tests/ds_memory_control/conf/diff_config.toml
  tests/integration_tests/ds_memory_control/conf/workload
  tests/integration_tests/ds_memory_control/conf/workload-2
  tests/integration_tests/ds_memory_control/run.sh
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/parallel_dynamic_stream.go
  utils/dynstream/stream.go
  utils/dynstream/stream_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1006 cmd: eliminate tiflow dependencies in cmd package
  api/v1/api.go
  api/v2/changefeed.go
  api/v2/model.go
  cmd/cdc/cli/cli.go
  cmd/cdc/cli/cli_capture_list.go
  cmd/cdc/cli/cli_changefeed_create.go
  cmd/cdc/cli/cli_changefeed_list.go
  cmd/cdc/cli/cli_changefeed_move_table.go
  cmd/cdc/cli/cli_changefeed_pause.go
  cmd/cdc/cli/cli_changefeed_query.go
  cmd/cdc/cli/cli_changefeed_remove.go
  cmd/cdc/cli/cli_changefeed_resume.go
  cmd/cdc/cli/cli_changefeed_statistics.go
  cmd/cdc/cli/cli_changefeed_update.go
  cmd/cdc/cli/cli_changefeed_update_test.go
  cmd/cdc/cli/cli_tso_query.go
  cmd/cdc/cli/cli_unsafe_delete_service_gc_safepoint.go
  cmd/cdc/cli/cli_unsafe_reset.go
  cmd/cdc/cli/cli_unsafe_resolve_lock.go
  cmd/cdc/cli/cli_unsafe_show_metadata.go
  cmd/cdc/factory/factory.go
  cmd/cdc/factory/factory_impl.go
  cmd/cdc/main.go
  cmd/cdc/server/server.go
  cmd/filter-helper/main.go
  cmd/kafka-consumer/option.go
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  cmd/util/util.go
  downstreamadapter/sink/cloudstorage.go
  logservice/eventstore/event_store.go
  logservice/logpuller/region_request_worker.go
  pkg/config/replica_config.go
  pkg/errors/error.go
  pkg/errors/helper.go
  pkg/eventservice/dispatcher_stat.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/sink/util/helper.go
  pkg/util/pointer.go
  pkg/util/tz.go
  tests/integration_tests/api_v2/cases.go
  tests/utils/checksum_checker/main.go
Labels: lgtm, approved, size/XXL, release-note-none

#1009 schemastore: ignore system schema
  logservice/schemastore/schema_store.go
Labels: lgtm, approved, release-note, size/XS

#1010 metrics: unify the metrics in dataflow to rows/s
  downstreamadapter/eventcollector/event_collector.go
  maintainer/replica/checker.go
  metrics/grafana/ticdc_new_arch.json
  pkg/common/event/ddl_event.go
  pkg/common/event/handshake_event.go
  pkg/common/event/interface.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/sync_point_event.go
Labels: lgtm, approved, size/M, release-note-none

#1014 test: fix canal_json_storage test
  pkg/sink/codec/canal/encoder.go
  tests/integration_tests/canal_json_storage_partition_table/conf/diff_config.toml
Labels: lgtm, approved, size/S, release-note-none

#1016 Add log for debug
  pkg/sink/mysql/mysql_writer_dml.go
Labels: lgtm, approved, release-note, size/XS

#1015 mysql-sink: support conflict detector for mysql sink
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/sink/blackhole.go
  downstreamadapter/sink/cloudstorage.go
  downstreamadapter/sink/conflictdetector/conflict_detector.go
  downstreamadapter/sink/conflictdetector/helper.go
  downstreamadapter/sink/conflictdetector/node.go
  downstreamadapter/sink/conflictdetector/slot.go
  downstreamadapter/sink/conflictdetector/txn_cache.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/sink/mysql_sink.go
  downstreamadapter/sink/sink.go
  downstreamadapter/worker/mysql_worker.go
  pkg/common/event/dml_event.go
  pkg/common/table_info.go
Labels: lgtm, approved, size/XXL, release-note-none

#1018 Fix the worker-count of mysql sink
  downstreamadapter/sink/mysql_sink.go
  downstreamadapter/sink/sink.go
  pkg/sink/mysql/config.go
Labels: lgtm, approved, release-note, size/XS

#1019 Add some logs and adjust the param for split table
  api/v2/model.go
  downstreamadapter/eventcollector/helper.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/replica/checker.go
  maintainer/replica/checker_test.go
  maintainer/scheduler.go
  maintainer/split/region_count_splitter.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/splitter.go
  maintainer/split/write_bytes_splitter.go
  maintainer/split/write_bytes_splitter_test.go
  pkg/config/replica_config.go
  pkg/config/scheduler_config.go
Labels: lgtm, approved, release-note, size/L

#1021 puller: add tikv version check
  Makefile
  api/v2/changefeed.go
  api/v2/status.go
  cmd/cdc/factory/factory_impl.go
  cmd/cdc/server/server.go
  cmd/cdc/version/version.go
  cmd/kafka-consumer/main.go
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  logservice/logpuller/errors.go
  logservice/logpuller/mock_upstream.go
  logservice/logpuller/region_request_worker.go
  pkg/api/internal/rest/request.go
  pkg/config/changefeed.go
  pkg/node/node.go
  pkg/version/check.go
  pkg/version/check_test.go
  pkg/version/creator_version_gate.go
  pkg/version/creator_version_gate_test.go
  pkg/version/version.go
  tests/integration_tests/api_v2/request.go
Labels: lgtm, approved, release-note, size/XXL

#1025 ci: refactor integration tests running scripts in ci
  tests/integration_tests/_utils/check_coverage.sh
  tests/integration_tests/run.sh
  tests/integration_tests/run_group.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XXL, release-note-none

#1031 maintainer: use ticker to generate periodEvent
  maintainer/maintainer.go
  maintainer/maintainer_test.go
Labels: lgtm, approved, size/M, release-note-none

#1029 puller: small improvement
  logservice/logpuller/errors.go
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/subscription_client.go
  server/server.go
Labels: lgtm, approved, release-note, size/M

#1034 ci: fix typo in run_light_it_in_ci.sh (chartset_gbk → charset_gbk)
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XS, release-note-none

#1038 ci: fix ci by enable TICDC_NEWARCH for new arch
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XS, release-note-none

#1036 Don't merge spans when the checkpoint lag is large
  maintainer/maintainer_controller_test.go
  maintainer/replica/checker.go
  pkg/pdutil/clock.go
Labels: lgtm, approved, release-note, size/M

#1032 Fix the wrong update of checkpointTs
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  maintainer/barrier.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/operator/operator_controller.go
Labels: lgtm, approved, release-note, size/M

#1047 ci: add check to validate test cases in groups
  tests/integration_tests/_utils/check_coverage.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1049 puller: improve write performance for single large table
  logservice/eventstore/event_store.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/subscription_client.go
Labels: lgtm, approved, release-note, size/M

#1051 ci: remove check_coverage.sh exit before all missing test added
  tests/integration_tests/_utils/check_coverage.sh
Labels: lgtm, approved, size/XS, release-note-none

#1043 sink: fix topic dispatchers for renaming tables
  pkg/common/event/ddl_event.go
Labels: lgtm, approved, size/S, release-note-none

#1035 sink: add checkpointTs message for storage sink
  coordinator/changefeed/changefeed.go
  coordinator/changefeed/changefeed_db_test.go
  coordinator/changefeed/changefeed_test.go
  coordinator/controller_test.go
  coordinator/coordinator.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/codec/csv/csv_message.go
Labels: lgtm, approved, size/M, release-note-none

#1057 schemastore: improve unit tests
  logservice/schemastore/multi_version_test.go
  logservice/schemastore/persist_storage_test.go
Labels: lgtm, approved, size/XL, release-note

#1039 coordinator: send checkpointTs message when changefeed state is finished
  coordinator/controller.go
  coordinator/coordinator.go
  coordinator/helper.go
Labels: lgtm, approved, size/L, release-note-none
