Repository pingcap/ticdc, pull requests merged in 2025-08, with the labels that each got.

#1602 eventcollector: avoid drop local messages
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  logservice/eventstore/event_store.go
Labels: lgtm, approved, release-note, size/L

#1609 consumer: avoid panic when execute ddl failed
  cmd/kafka-consumer/writer.go
  cmd/pulsar-consumer/writer.go
Labels: lgtm, approved, release-note, size/XS

#1403 Support output rowkey in canal json
  pkg/common/event/dml_event.go
  pkg/config/sink.go
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/common/config.go
Labels: lgtm, approved, first-time-contributor, size/L, release-note-none

#1619 cmd: patch tidb config set tikvclient max batch size to 0
  cmd/cdc/server/server.go
  logservice/logpuller/region_event_handler.go
Labels: lgtm, approved, size/S, release-note-none

#1623 dispatcher: fix incorrect watermark when collecting component status
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
Labels: lgtm, approved, size/S, release-note-none

#1627 *: improve memory quota metrics
  logservice/eventstore/event_store.go
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/M

#1629 dispatcher: avoid replicating ddl events in bdr secondary role
  downstreamadapter/dispatcher/dispatcher_block_event.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  pkg/eventservice/event_broker.go
Labels: lgtm, approved, size/M, release-note-none

#1632 cli: fix typo in the help message for the --user flag
  cmd/cdc/factory/factory.go
Labels: lgtm, approved, first-time-contributor, needs-ok-to-test, size/XS, release-note-none, contribution

#1643 ddl: Fixed a DDL corner case in table splitting scenarios
  maintainer/barrier_event.go
  maintainer/barrier_test.go
Labels: lgtm, approved, size/XL, release-note

#1650 logcoordinator: ignore down nodes
  logservice/coordinator/coordinator.go
  logservice/coordinator/coordinator_test.go
Labels: lgtm, approved, release-note, size/M

#1656 *: fix table info private fields not initialized
  downstreamadapter/eventcollector/dispatcher_stat.go
Labels: lgtm, approved, release-note, size/XS

#1655 *: minor refactor to make code cleaner
  downstreamadapter/dispatcher/basic_dispatcher.go
  downstreamadapter/dispatcher/basic_dispatcher_info.go
  downstreamadapter/dispatcher/event_dispatcher.go
  downstreamadapter/dispatcher/event_dispatcher_test.go
  downstreamadapter/dispatcher/redo_dispatcher.go
  downstreamadapter/dispatcher/redo_dispatcher_test.go
  downstreamadapter/dispatcher/table_progress.go
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  downstreamadapter/dispatchermanager/dispatcher_manager_helper.go
  downstreamadapter/dispatchermanager/dispatcher_manager_info.go
  downstreamadapter/dispatchermanager/dispatcher_manager_redo.go
  downstreamadapter/dispatchermanager/dispatcher_manager_test.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/sink/kafka/sink.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  maintainer/split/splitter.go
  maintainer/split/write_bytes_splitter.go
  maintainer/split/write_bytes_splitter_test.go
  pkg/common/context/app_context.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_benchmark.go
  pkg/common/event/mounter_test.go
  pkg/common/event/util.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service_test.go
  pkg/sink/cloudstorage/table_definition_test.go
  pkg/sink/codec/avro/arvo.go
  pkg/sink/codec/bootstraper.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message_test.go
  server/server.go
  server/server_prepare.go
Labels: lgtm, approved, release-note, size/XXL

#1692 *: fix unstable tests
  cmd/kafka-consumer/writer.go
  cmd/pulsar-consumer/writer.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  pkg/common/event/dml_event.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
Labels: lgtm, approved, release-note, size/M

#1678 filter: Fix sharing filter after update config
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/messaging/message.go
Labels: lgtm, approved, size/XL, release-note

#1664 *: Eliminate tiflow dependencies
  cmd/kafka-consumer/event_group.go
  cmd/pulsar-consumer/event_group.go
  cmd/pulsar-consumer/main.go
  cmd/pulsar-consumer/options.go
  coordinator/changefeed/changefeed.go
  downstreamadapter/sink/helper/helper.go
  downstreamadapter/sink/redo/meta.go
  downstreamadapter/sink/sink.go
  maintainer/maintainer.go
  maintainer/operator/operator_controller.go
  pkg/config/changefeed.go
  pkg/config/messages.go
  pkg/config/outdated/v1.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/config/sink_protocol.go
  pkg/logger/log.go
  pkg/redo/reader/file_test.go
  pkg/redo/reader/reader.go
  pkg/redo/writer/memory/mem_log_writer.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/codec/builder.go
  pkg/sink/mysql/config.go
  pkg/sink/pulsar/config.go
Labels: lgtm, approved, size/XL, release-note-none

#1666 test: fix diff_config and add unit tests
  downstreamadapter/eventcollector/dispatcher_stat.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_test.go
  tests/integration_tests/ddl_attributes/conf/diff_config.toml
  tests/integration_tests/ddl_for_split_tables/conf/diff_config.toml
  tests/integration_tests/ddl_for_split_tables_with_failover/conf/diff_config.toml
  tests/integration_tests/ddl_for_split_tables_with_merge_and_split/conf/diff_config.toml
  tests/integration_tests/ddl_reentrant/conf/diff_config.toml
  tests/integration_tests/ddl_sequence/conf/diff_config.toml
  tests/integration_tests/ddl_wait/conf/diff_config.toml
  tests/integration_tests/ddl_with_random_move_table/conf/diff_config.toml
Labels: lgtm, approved, release-note, size/M

#1688 feat(Makefile): add `integration_test_build_fast` for faster developer iteration
  Makefile
Labels: lgtm, approved, size/S, release-note-none

#1782 eventcollector: ignore same syncpoint
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
Labels: lgtm, approved, size/M, release-note-none

#1815 event: fix syncpoint event encoding
  pkg/common/event/sync_point_event.go
  pkg/common/event/sync_point_event_test.go
  pkg/eventservice/event_broker.go
Labels: lgtm, approved, release-note, size/M

#1714 conflictDectector: Fix data race
  downstreamadapter/sink/mysql/causality/conflict_detector.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
Labels: lgtm, approved, size/S, release-note

#1830 test: fix unstable test
  downstreamadapter/sink/cloudstorage/dml_writers_test.go
  tests/integration_tests/fail_over/run.sh
Labels: lgtm, approved, size/S, release-note
