Repository pingcap/ticdc, pull requests merged in 2025-10, with the labels that each got.

#2433 eventfilter: support event filter with virtual column
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/filter/expr_filter.go
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/run.sh
Labels: lgtm, approved, release-note, size/L

#2456 tests: add OnNodeRemove unit tests for all operator types
  maintainer/operator/operator_add_test.go
  maintainer/operator/operator_merge_test.go
  maintainer/operator/operator_occupy_test.go
  maintainer/operator/operator_remove.go
  maintainer/operator/operator_remove_test.go
  maintainer/operator/operator_split_test.go
Labels: lgtm, approved, size/XL, release-note

#2460 workload: Added delete statement in all workload
  tools/workload/app.go
  tools/workload/config.go
  tools/workload/delete.go
  tools/workload/schema/bank/bank.go
  tools/workload/schema/bank2/bank2.go
  tools/workload/schema/bankupdate/bank_update.go
  tools/workload/schema/crawler/crawler.go
  tools/workload/schema/interface.go
  tools/workload/schema/largerow/large_row.go
  tools/workload/schema/shop/shop.go
  tools/workload/schema/sysbench/sysbench.go
  tools/workload/schema/uuu/uuu.go
Labels: lgtm, approved, release-note, size/XXL

#2461 eventstore&eventbroker: fix dead lock
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
Labels: lgtm, approved, release-note, size/L

#2477 eventstore: add metric for dispatcher startTs lag at register
  logservice/eventstore/event_store.go
  metrics/grafana/ticdc_new_arch.json
  pkg/metrics/event_store.go
Labels: lgtm, approved, release-note, size/L

#2478 schemastore: add wait resolved ts metrics
  logservice/schemastore/schema_store.go
  metrics/grafana/ticdc_new_arch.json
  pkg/metrics/schema_store.go
Labels: lgtm, approved, release-note, size/L

#2475 dispatcherManager: Use threadpool to asynchronously handle remove dispatcher
  downstreamadapter/dispatchermanager/dispatcher_manager.go
  downstreamadapter/dispatchermanager/dispatcher_manager_helper.go
  downstreamadapter/dispatchermanager/task.go
Labels: lgtm, approved, release-note, size/L

#2489 logCoordinator: use a new etcd key to avoid panic when rollback to old arch ticdc
  pkg/etcd/etcdkey.go
  server/module_election.go
Labels: lgtm, approved, size/S, release-note

#2494 eventstore: avoid useless scan when dispatcher for empty tables initialize
  logservice/eventstore/event_store.go
Labels: lgtm, approved, release-note, size/XS

#2515 eventbroker: remove timeout in scan limit
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
Labels: lgtm, approved, release-note, size/M
