Repository pingcap/ticdc, pull requests merged in 2025-07, with the labels that each got.

#1485 eventcollector: split resolvedTs and DML event
  downstreamadapter/eventcollector/helper.go
  tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1495 eventCollector: allow resolvedTs and dml event in the same batch
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/eventcollector/helper.go
Labels: lgtm, approved, size/S, release-note

#1498 eventcollector: support batch process for BatchDMLEvents
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/helper.go
Labels: lgtm, approved, release-note, size/L

#1491 eventCollector: fix a bug related to dropEvent.
  README.md
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/eventcollector/helper.go
  utils/dynstream/memory_control.go
Labels: lgtm, approved, size/S, release-note

#1502 *: introduces new Splitable property for tables
  heartbeatpb/heartbeat.pb.go
  heartbeatpb/heartbeat.proto
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/utils.go
  logservice/schemastore/utils_test.go
  maintainer/barrier_event.go
  maintainer/barrier_event_test.go
  maintainer/maintainer_controller_bootstrap.go
  maintainer/span/span_controller.go
  pkg/common/event/interface.go
  pkg/common/event/util.go
Labels: lgtm, approved, release-note, size/XXL

#1511 eventbroker: fix syncpoint seq
  pkg/eventservice/event_broker.go
Labels: lgtm, approved, release-note, size/XS

#1513 *: fix pd dependency version
  cmd/cdc/factory/factory_impl.go
  go.mod
  go.sum
  logservice/logpuller/mock_upstream.go
  pkg/migrate/migrate.go
  pkg/pdutil/api_client.go
  pkg/txnutil/gc/testing.go
  pkg/upstream/upstream.go
  pkg/version/check.go
  pkg/version/check_test.go
  server/server_prepare.go
  tests/integration_tests/resolve_lock/main.go
Labels: lgtm, approved, release-note, size/L

#1497 change data size from int64 to uint64
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatcher/table_progress.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/helper.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/writer.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/redo/sink.go
  logservice/logpuller/region_event_handler.go
  pkg/common/event/ddl_event.go
  pkg/common/event/dispatcher_heartbeat.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/common/event/dml_event.go
  pkg/common/event/drop_event.go
  pkg/common/event/handshake_event.go
  pkg/common/event/interface.go
  pkg/common/event/not_reusable_event.go
  pkg/common/event/not_reusable_event_test.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/sync_point_event.go
  pkg/common/types.go
  pkg/metrics/statistics.go
  pkg/node/node.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_test.go
  pkg/sink/mysql/sql_builder.go
  utils/dynstream/dynamic_stream_bench_test.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_algorithm.go
  utils/dynstream/memory_control_algorithm_test.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/parallel_dynamic_stream.go
  utils/dynstream/stream.go
  utils/dynstream/stream_bench_test.go
  utils/dynstream/stream_test.go
Labels: lgtm, approved, size/XL, release-note-none

#1523 eventbroker: filter out invalid resolved ts
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker_test.go
Labels: lgtm, approved, size/S, release-note

#1520 sink: add error check in kafka sink initialization
  downstreamadapter/sink/kafka/helper.go
Labels: lgtm, approved, release-note, size/XS

#1527 eventstore: fix input write bytes metrics
  logservice/eventstore/event_store.go
  metrics/grafana/ticdc_new_arch.json
  pkg/metrics/event_store.go
Labels: lgtm, approved, size/S, release-note

#1531 test: recover `fail_over_ddl_mix_with_syncpoint` intergration test
  tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, size/S, release-note

#1540 Revert "change data size from int64 to uint64 (#1497)"
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatcher/table_progress.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/helper.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/writer.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/redo/sink.go
  logservice/logpuller/region_event_handler.go
  pkg/common/event/ddl_event.go
  pkg/common/event/dispatcher_heartbeat.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/common/event/dml_event.go
  pkg/common/event/drop_event.go
  pkg/common/event/handshake_event.go
  pkg/common/event/interface.go
  pkg/common/event/not_reusable_event.go
  pkg/common/event/not_reusable_event_test.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/sync_point_event.go
  pkg/common/types.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/metrics/statistics.go
  pkg/node/node.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_test.go
  pkg/sink/mysql/sql_builder.go
  utils/dynstream/dynamic_stream_bench_test.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_algorithm.go
  utils/dynstream/memory_control_algorithm_test.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/parallel_dynamic_stream.go
  utils/dynstream/stream.go
  utils/dynstream/stream_bench_test.go
  utils/dynstream/stream_test.go
Labels: lgtm, approved, size/XL, release-note

#1543 eventcollector: avoid remove & add path when reset dispatcher
  downstreamadapter/eventcollector/dispatcher_stat.go
Labels: lgtm, approved, size/S, release-note

#1486 test: add more storage integration tests
  Makefile
  cmd/storage-consumer/main.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/sink/cloudstorage/defragmenter_test.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/dml_writers_test.go
  downstreamadapter/sink/cloudstorage/sink.go
  downstreamadapter/sink/cloudstorage/sink_test.go
  downstreamadapter/sink/cloudstorage/writer.go
  downstreamadapter/worker/cloudstorage_ddl_worker.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/dml_event.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/eventservice/event_broker.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/codec/canal/canal_json_encoder.go
  tests/integration_tests/generate_column/conf/changefeed.toml
  tests/integration_tests/move_table/main.go
  tests/integration_tests/multi_rocks/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XL, release-note-none

#1539 sink(ticdc): calculate partition by the orignal column name
  downstreamadapter/sink/eventrouter/partition/column_test.go
  downstreamadapter/sink/eventrouter/partition/columns.go
  downstreamadapter/sink/eventrouter/partition/index_value.go
  downstreamadapter/sink/eventrouter/partition/index_value_test.go
  pkg/common/table_info.go
Labels: lgtm, approved, size/M, release-note-none

#1551 log: degrade the log level to avoid too many useless log
  downstreamadapter/dispatcher/basic_dispatcher.go
  tests/integration_tests/_utils/check_logs
Labels: lgtm, approved, size/S, release-note

#1563 DS: fix a bug in memory control
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/stream.go
Labels: lgtm, approved, size/M, release-note-none

#1556 codec: fix panic in kafka_simple_basic integration test
  cmd/kafka-consumer/writer.go
  pkg/sink/codec/simple/decoder.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1574 eventstore: reduce ttl of idle subscriptions
  logservice/eventstore/event_store.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, release-note, size/XS

#1572 eventCollector: adjust verbos log
  downstreamadapter/eventcollector/helper.go
Labels: lgtm, approved, size/XS, release-note-none

#1577 eventcollector: ignore the heartbeat for dispatchers which are not receving data
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  pkg/messaging/message_center.go
  pkg/node/node.go
Labels: lgtm, approved, size/S, release-note

#1578 messagecenter: fix goroutine leak when remote connection are reset
  downstreamadapter/eventcollector/log_coordinator_client.go
  pkg/messaging/remote_target.go
Labels: lgtm, approved, release-note, size/L

#1580 coordinator: cut down the long error message info to avoid error `ResourceExhausted` occurs when interacting with etcd
  pkg/config/changefeed.go
Labels: lgtm, approved, release-note, size/XS

#1582 Remove changefeed more quickly
  coordinator/controller.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
Labels: lgtm, approved, release-note, size/M

#1589 event: dml size correctly calculated by using the chunk memory usage method instead of the raw entry size
  cmd/kafka-consumer/event_group.go
  cmd/pulsar-consumer/event_group.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/redo/sink.go
  pkg/common/event/dml_event.go
  pkg/common/kv_entry.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/metrics/event_service.go
  pkg/sink/codec/canal/canal_json_txn_decoder.go
  pkg/sink/mysql/mysql_writer_dml.go
Labels: lgtm, approved, size/M, release-note-none
