Repository pingcap/ticdc, pull requests merged in 2025-06, with the labels that each got.

#1392 eventBroker: fix out-of-order issue with DML events and syncpoint events
  pkg/common/event/dml_event.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_service_test.go
Labels: lgtm, approved, release-note, size/L

#1393 log: add some log for debug merge-split operator
  maintainer/operator/operator_merge_split.go
Labels: lgtm, approved, release-note, size/XS

#1375 eventBroker: support split update event that UK changed
  Makefile
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/sink/kafka/sink.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/chunk.go
  pkg/common/event/codec.go
  pkg/common/event/codec_test.go
  pkg/common/event/ddl_event.go
  pkg/common/event/ddl_event_test.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_benchmark.go
  pkg/common/event/dml_event_test.go
  pkg/common/event/handshake_event.go
  pkg/common/event/interface.go
  pkg/common/event/mounter_test.go
  pkg/common/event/not_reusable_event.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/util.go
  pkg/common/kv_entry.go
  pkg/common/kv_entry_test.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/eventservice/metrics_collector.go
  pkg/metrics/event_service.go
Labels: lgtm, approved, size/XXL, release-note-none

#1351 dispatcher,maintainer: Support Merge Dispatchers without obvious lag
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_info.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager_test.go
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/dispatchermanager/task.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/sink/mock_sink.go
  heartbeatpb/heartbeat.pb.go
  heartbeatpb/heartbeat.proto
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/operator/operator_controller.go
  maintainer/operator/operator_empty.go
  maintainer/operator/operator_merge.go
  maintainer/replica/replication_db.go
  pkg/apperror/errors.go
  pkg/common/table_span.go
  pkg/messaging/helper.go
  pkg/messaging/message.go
  pkg/messaging/message_center_integration_test.go
  tests/integration_tests/merge_table/conf/changefeed.toml
  tests/integration_tests/merge_table/conf/diff_config.toml
  tests/integration_tests/merge_table/data/pre.sql
  tests/integration_tests/merge_table/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, release-note, size/XXL

#1414 *: use atomic value to store coordinator info
  downstreamadapter/eventcollector/event_collector.go
  logservice/eventstore/event_store.go
Labels: lgtm, approved, size/S, release-note

#1419 eventCollector: fix a panic
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  tests/scripts/download-integration-test-binaries.sh
Labels: lgtm, approved, size/S, release-note-none

#1420 metrics: add more new metrics about the event service
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
  metrics/grafana/ticdc_new_arch.json
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/eventservice/metrics_collector.go
  pkg/metrics/event_service.go
Labels: lgtm, approved, size/XXL, release-note-none

#1429 revert temporary changes
  tests/scripts/download-integration-test-binaries.sh
Labels: lgtm, approved, size/XS, release-note-none

#1421 eventcollector: refactor event handle logic
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/eventcollector/event_collector_test.go
  downstreamadapter/eventcollector/helper.go
  downstreamadapter/eventcollector/log_coordinator_client.go
  logservice/coordinator/coordinator.go
  logservice/schemastore/persist_storage.go
  pkg/eventservice/event_broker.go
  pkg/messaging/topic.go
Labels: lgtm, approved, release-note, size/XXL

#1422 *: correct handle key in table info
  pkg/common/table_info_helper.go
  pkg/common/table_info_helper_test.go
Labels: lgtm, approved, size/M, release-note-none

#1432 dispatcher: fix panic in conflict detector
  downstreamadapter/sink/mysql/causality/conflict_detector.go
Labels: lgtm, approved, release-note, size/XS

#1412 mounter: fix incorrect row when verifing checksum
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_info.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager_test.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector_test.go
  pkg/common/event/checksum.go
  pkg/common/event/mounter.go
  pkg/common/event/mounter_test.go
  pkg/config/changefeed.go
  pkg/config/integrity.go
  pkg/config/sink.go
  pkg/sink/codec/common/verify_checksum.go
  tests/integration_tests/kafka_simple_basic/data/data.sql
Labels: lgtm, approved, size/L, release-note-none

#1438 Add log for dispatcher handle events
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/helper.go
Labels: lgtm, approved, release-note, size/XS

#1430 DS, eventCollector: drop event if needed
  Makefile
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/eventcollector/event_collector_test.go
  downstreamadapter/eventcollector/helper.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/subscription_client.go
  pkg/common/event/ddl_event.go
  pkg/common/event/dml_event.go
  pkg/common/event/drop_event.go
  pkg/common/event/drop_event_test.go
  pkg/common/event/handshake_event.go
  pkg/common/event/interface.go
  pkg/common/event/not_reusable_event.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_service_test.go
  pkg/metrics/dispatcher.go
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/multi_capture/run.sh
  tests/integration_tests/syncpoint/run.sh
  utils/dynstream/dynamic_stream_bench_test.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_algorithm.go
  utils/dynstream/memory_control_algorithm_test.go
  utils/dynstream/memory_control_test.go
  utils/dynstream/stream_bench_test.go
  utils/dynstream/stream_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1453 minor refine the code of maintainer
  coordinator/changefeed/changefeed.go
  maintainer/barrier.go
  maintainer/barrier_event.go
  maintainer/barrier_test.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_bootstrap.go
  maintainer/maintainer_controller_helper.go
  maintainer/maintainer_manager.go
  maintainer/operator/operator_add.go
Labels: lgtm, approved, release-note, size/XXL

#1459 coordinator: fix a data race in changefeed
  coordinator/changefeed/changefeed.go
Labels: lgtm, approved, size/XS, release-note-none

#1454 dispatcher: fix bug in wakeCallback
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/sink/mock_sink.go
Labels: lgtm, approved, release-note, size/L

#1462 Make merge operator tool more robust
  maintainer/maintainer_controller_helper.go
  maintainer/operator/operator_controller.go
Labels: lgtm, approved, size/S, release-note

#1442 redo: rewrite writer and move to pkg
  pkg/common/event/redo.go
  pkg/redo/codec/codec.go
  pkg/redo/codec/codec_test.go
  pkg/redo/common/main_test.go
  pkg/redo/common/metric.go
  pkg/redo/common/redo_meta.go
  pkg/redo/common/redo_meta_gen.go
  pkg/redo/common/redo_meta_gen_test.go
  pkg/redo/common/util.go
  pkg/redo/common/util_test.go
  pkg/redo/config.go
  pkg/redo/main_test.go
  pkg/redo/reader/blackhole_reader.go
  pkg/redo/reader/file.go
  pkg/redo/reader/file_test.go
  pkg/redo/reader/main_test.go
  pkg/redo/reader/reader.go
  pkg/redo/reader/reader_test.go
  pkg/redo/writer/blackhole/blackhole_log_writer.go
  pkg/redo/writer/factory/factory.go
  pkg/redo/writer/file/file.go
  pkg/redo/writer/file/file_log_writer.go
  pkg/redo/writer/file/file_log_writer_test.go
  pkg/redo/writer/file/file_test.go
  pkg/redo/writer/file/main_test.go
  pkg/redo/writer/file/mock_fileWriter.go
  pkg/redo/writer/memory/file_worker.go
  pkg/redo/writer/memory/main_test.go
  pkg/redo/writer/memory/mem_log_writer.go
  pkg/redo/writer/memory/mem_log_writer_test.go
  pkg/redo/writer/writer.go
  redo/manager.go
  redo/manager_test.go
  redo/meta_manager.go
  redo/meta_manager_test.go
  redo/writer/file/mock_fileWriter.go
  redo/writer/memory/encoding_worker.go
Labels: lgtm, approved, size/XXL, release-note-none

#1464 *: adjust some code fix some tiny problem
  cmd/kafka-consumer/writer.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/mysql/causality/helper.go
  pkg/common/table_info_helper.go
  pkg/compression/compress.go
  pkg/errors/error.go
  pkg/sink/mysql/mysql_writer_ddl.go
Labels: lgtm, approved, size/M, release-note-none

#1465 event service: read code and some tiny refactor
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  logservice/eventstore/event_store.go
  logservice/schemastore/schema_store.go
  pkg/common/event/dispatcher_heartbeat.go
  pkg/common/event/dispatcher_heartbeat_test.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_test.go
  pkg/common/event/handshake_event.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/resolved_ts_event_test.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/eventservice/metrics_collector.go
  utils/dynstream/interfaces.go
  utils/dynstream/parallel_dynamic_stream.go
  utils/dynstream/stream.go
Labels: lgtm, approved, size/XXL, release-note-none

#1469 eventboker: send data events immediately after handshake event
  downstreamadapter/eventcollector/event_collector_test.go
  pkg/common/event/handshake_event.go
  pkg/common/event/handshake_event_test.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/dispatcher_stat_test.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/metrics_collector.go
Labels: lgtm, approved, release-note, size/L

#1470 Set regionCache as a global shared component in appcontext
  logservice/logpuller/subscription_client.go
  logservice/logpuller/subscription_client_test.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  maintainer/split/region_count_splitter.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/splitter.go
  pkg/common/context/app_context.go
  server/server.go
  server/server_prepare.go
Labels: lgtm, approved, release-note, size/L

#1475 schemastore: support add fulltext index
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/binlog-filter/filter.go
  pkg/filter/ddl.go
Labels: lgtm, approved, size/S, release-note

#1478 event: add seq to syncpoint event
  downstreamadapter/eventcollector/dispatcher_stat.go
  pkg/common/event/sync_point_event.go
  pkg/eventservice/event_broker.go
Labels: lgtm, approved, size/S, release-note

#1474 common: correct the table info when retrieving without virtual columns
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/sqlmodel/multi_row.go
Labels: lgtm, approved, size/L, release-note-none

#1466 Check result for adding operator in operator controller
  maintainer/maintainer_controller_helper.go
Labels: lgtm, approved, size/S, release-note

#1484 eventcollector: use epoch to filter out invalid events
  downstreamadapter/dispatchermanager/event_dispatcher_manager_test.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/dispatcher_stat_test.go
  downstreamadapter/eventcollector/event_collector_test.go
  downstreamadapter/eventcollector/helper.go
  eventpb/event.pb.go
  eventpb/event.proto
  pkg/common/event/ddl_event.go
  pkg/common/event/dml_event.go
  pkg/common/event/drop_event.go
  pkg/common/event/drop_event_test.go
  pkg/common/event/handshake_event.go
  pkg/common/event/handshake_event_test.go
  pkg/common/event/interface.go
  pkg/common/event/not_reusable_event.go
  pkg/common/event/ready_event.go
  pkg/common/event/resolved_ts_event.go
  pkg/common/event/sync_point_event.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/messaging/message.go
Labels: lgtm, approved, release-note, size/XXL
