Repository pingcap/ticdc, pull requests merged in 2025-03, with the labels that each got.

#1056 eventstore: remove zstd and adjust pebble options
  go.mod
  logservice/eventstore/event_store.go
  logservice/eventstore/pebble.go
  logservice/eventstore/pebble_test.go
Labels: lgtm, approved, size/XL, release-note

#1058 test: fix multi_topics test
  downstreamadapter/sink/helper/eventrouter/topic/topic.go
  downstreamadapter/sink/helper/topicmanager/kafka_topic_manager.go
  downstreamadapter/worker/mq_ddl_worker.go
  pkg/sink/util/helper.go
  pkg/sink/util/helper_test.go
  tests/integration_tests/multi_topics/run.sh
  tests/integration_tests/multi_topics_v2/run.sh
Labels: lgtm, approved, size/M, release-note-none

#1054 maintainer: refactor maintainer and controller
  coordinator/operator/operator_controller.go
  maintainer/barrier_event.go
  maintainer/barrier_event_test.go
  maintainer/barrier_test.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  maintainer/operator/operator_controller.go
  maintainer/operator/operator_remove.go
  maintainer/replica/checker_test.go
  maintainer/replica/mock/tso_client.go
  maintainer/replica/replication_db.go
  maintainer/replica/replication_db_test.go
  maintainer/replica/replication_span.go
  maintainer/replica/replication_span_test.go
  maintainer/replica/tso_client.go
  maintainer/scheduler.go
  pkg/pdutil/clock.go
  pkg/pdutil/clock_test.go
  pkg/scheduler/basic.go
  pkg/scheduler/operator/operator.go
  pkg/scheduler/operator/operator_queue.go
  pkg/scheduler/operator/operator_queue_test.go
  pkg/scheduler/replica/checker.go
  pkg/scheduler/replica/replication.go
  pkg/scheduler/scheduler.go
  server/server.go
  utils/threadpool/task.go
Labels: lgtm, approved, size/XXL, release-note-none

#1064 Fix deadlock of maintainer
  pkg/scheduler/replica/replication.go
Labels: lgtm, approved, size/S, release-note

#1028 Support batch dmls across the events
  downstreamadapter/eventcollector/helper.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/sink/mysql/mysql_writer_test.go
  pkg/sink/sqlmodel/utils.go
Labels: lgtm, approved, release-note, size/XXL

#1065 puller: fix panic
  logservice/logpuller/region_event_handler.go
Labels: lgtm, approved, release-note, size/XS

#1052 Support bank2 workload
  tools/workload/main.go
  tools/workload/schema/bank2.go
Labels: lgtm, approved, release-note, size/XXL

#1066 puller: fix potential stuck
  logservice/logpuller/region_request_worker.go
Labels: lgtm, approved, release-note, size/XS

#1063 test: Add unit test for cloudstorage sink
  Makefile
  downstreamadapter/sink/cloudstorage_test.go
  downstreamadapter/worker/cloudstorage_ddl_worker_test.go
  downstreamadapter/worker/cloudstorage_dml_worker_test.go
  downstreamadapter/worker/writer/defragmenter_test.go
  downstreamadapter/worker/writer/worker_test.go
  downstreamadapter/worker/writer/writer.go
  downstreamadapter/worker/writer/writer_test.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/cloudstorage/table_definition_test.go
  pkg/sink/codec/csv/csv_encoder_test.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/util/util.go
Labels: lgtm, approved, size/XXL, release-note-none

#1070 test: fix multi_source test
  tests/integration_tests/multi_source/main.go
Labels: lgtm, approved, size/XS, release-note-none

#1073 *: update tiflow dependency
  downstreamadapter/worker/writer/writer.go
  go.mod
  go.sum
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/schema_store.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/kafka/claimcheck/claim_check.go
Labels: lgtm, approved, release-note, size/L

#1071 For bug in sync point test
  maintainer/barrier_event.go
Labels: lgtm, approved, release-note, size/XS

#1072 Fix generation of syncpoint event
  pkg/eventservice/event_broker.go
Labels: lgtm, approved, release-note, size/XS

#1076 makefile: add prepare_test_binaries target to Makefile
  Makefile
Labels: lgtm, approved, size/XS, release-note-none

#1078 cli_tls_with_auth: enable_table_across_nodes should be true in mysql after supported
  tests/integration_tests/cli_tls_with_auth/run.sh
Labels: lgtm, approved, size/S, release-note-none

#1080 puller: fix dead lock
  logservice/logpuller/subscription_client.go
Labels: lgtm, approved, size/S, release-note

#1083 cli_with_auth: enable_table_across_nodes should be true in mysql after supported
  tests/integration_tests/cli_with_auth/run.sh
Labels: lgtm, approved, size/S, release-note-none

#1079 Fix unstable test changefeed_dup_error_restart
  pkg/sink/mysql/mysql_writer_test.go
  tests/integration_tests/changefeed_dup_error_restart/run.sh
Labels: lgtm, approved, size/S, release-note

#1060 redo: add redo relative messages
  pkg/common/event/redo.go
  pkg/common/event/redo_gen.go
  pkg/common/event/redo_gen_compatibility_test.go
  pkg/common/event/redo_gen_test.go
  pkg/common/table_info.go
  pkg/common/table_name.go
  pkg/common/table_name_gen.go
  pkg/common/table_name_gen_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1004 Fix docs of ds
  utils/dynstream/interfaces.go
  utils/dynstream/stream.go
Labels: lgtm, approved, size/S, release-note-none

#1090 ci: refactor mysql it groups to optimize resource allocation and cost of time
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1086 *: remove some unused code and refactor
  cmd/cdc/server/server.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  pkg/common/event/dml_event.go
  pkg/common/event/mounter.go
  pkg/common/event/row_change.go
  pkg/config/sink_protocol.go
  pkg/eventservice/event_broker.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/message.go
Labels: lgtm, approved, size/L, release-note-none

#1091 tableInfo: remove the schema ID field from the table info since it's not used
  downstreamadapter/worker/cloudstorage_ddl_worker_test.go
  downstreamadapter/worker/writer/defragmenter_test.go
  downstreamadapter/worker/writer/worker_test.go
  downstreamadapter/worker/writer/writer_test.go
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/disk_format.go
  logservice/schemastore/multi_version_test_utils.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  pkg/common/event/ddl_event_test.go
  pkg/common/event/redo_gen_compatibility_test.go
  pkg/common/event/util.go
  pkg/common/table_info.go
  pkg/eventservice/event_service_test.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
  pkg/sink/codec/csv/csv_message_test.go
Labels: lgtm, approved, size/L, release-note-none

#1094 metrics: add changefeed to panel `Sink Write Bytes`
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/XS

#1097 kafka: refactor the generator
  downstreamadapter/sink/helper/eventrouter/event_router.go
  downstreamadapter/sink/helper/eventrouter/event_router_test.go
  downstreamadapter/worker/mq_ddl_worker.go
  downstreamadapter/worker/mq_dml_worker.go
  pkg/common/event/chunk.go
  pkg/common/event/dml_event.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
Labels: lgtm, approved, size/L, release-note-none

#1099 eventstore: clean data after unsubscribe and add some metrics
  logservice/eventstore/event_store.go
  metrics/grafana/ticdc_new_arch.json
  pkg/metrics/event_store.go
Labels: lgtm, approved, release-note, size/XXL

#1101 codec: move some files to the corresponding folder and refactor canal-json encoder
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_txn_encoder.go
  pkg/sink/codec/canal/helper.go
  pkg/sink/codec/canal/java.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/open/encoder.go
  pkg/sink/codec/open/message.go
Labels: lgtm, approved, size/XXL, release-note-none

#1104 Fix unstable test `move table`
  maintainer/maintainer_controller.go
  pkg/apperror/errors.go
  tests/integration_tests/move_table/main.go
Labels: lgtm, approved, size/S, release-note

#1112 schemastore: fix drop partition table
  logservice/eventstore/event_store.go
  logservice/eventstore/pebble_test.go
  logservice/schemastore/multi_version_test.go
  logservice/schemastore/multi_version_test_utils.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
Labels: lgtm, approved, release-note, size/L

#1109 chore: update codes import
  downstreamadapter/worker/cloudstorage_dml_worker.go
  go.mod
  logservice/logpuller/utils.go
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/disk_format.go
  maintainer/maintainer.go
  pkg/compression/compress.go
  pkg/config/consistent.go
  pkg/config/large_message.go
  pkg/metrics/statistics.go
  pkg/sink/codec/common/compress.go
  server/server_prepare.go
Labels: lgtm, approved, size/L, release-note-none

#1110 workload: add a high throughput workload for testing.
  tools/workload/main.go
  tools/workload/schema/bank/bank.go
  tools/workload/schema/bank2/bank2.go
  tools/workload/schema/bankupdate/bank_update.go
  tools/workload/schema/bankupdate/readme.md
  tools/workload/schema/largerow/large_row.go
  tools/workload/schema/shop/shop.go
  tools/workload/schema/sysbench/sysbench.go
  tools/workload/schema/uuu/uuu.go
  tools/workload/util/util.go
Labels: lgtm, approved, size/XXL, release-note-none

#1120 tests: fix `region_merge` case.
  pkg/errors/error.go
  tests/integration_tests/_utils/check_contains
  tests/integration_tests/_utils/check_logs
  tests/integration_tests/_utils/check_not_contains
  tests/integration_tests/_utils/run_sql
  tests/integration_tests/_utils/run_sql_file
  tests/integration_tests/_utils/run_sql_ignore_error
  tests/integration_tests/region_merge/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
  tests/integration_tests/run_light_it_in_ci.sh
  tests/integration_tests/syncpoint/run.sh
  tests/integration_tests/syncpoint_check_ts/run.sh
Labels: lgtm, approved, size/M, release-note-none

#1123 ci: remove mysql integration tests from github actions
  .github/workflows/integration_test_mysql.yaml
Labels: lgtm, approved, size/XXL, release-note-none

#1129 *: update readme
  README.md
  docs/media/tiup-nightly-install.jpg
Labels: lgtm, approved, size/S, release-note

#1132 puller: fix dead lock
  logservice/logpuller/subscription_client.go
Labels: lgtm, approved, size/S, release-note-none

#1133 tests: fix integration test `multi_tables_ddl`
  coordinator/changefeed/backoff.go
  coordinator/controller.go
  tests/integration_tests/_utils/do_retry
  tests/integration_tests/multi_tables_ddl/run.sh
Labels: lgtm, approved, size/M, release-note-none

#961 Fix partition table ddl in mysql sink
  downstreamadapter/sink/mysql_sink_test.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/types.go
  logservice/schemastore/types_gen.go
  maintainer/replica/replication_span.go
  pkg/common/event/ddl_event.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_test.go
  tests/integration_tests/fail_over_ddl_mix/run.sh
  tests/integration_tests/partition_table/data/prepare.sql
Labels: lgtm, approved, size/XL, release-note

#1106 utils: skip workload schema hack
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/utils.go
Labels: lgtm, approved, first-time-contributor, size/M, release-note-none

#1136 tests: fix integration test `bank`
  logservice/schemastore/schema_store.go
  tests/integration_tests/bank/case.go
  tests/integration_tests/bank/run.sh
  tools/workload/main.go
Labels: lgtm, approved, size/L, release-note-none

#1135 *: modify cdc binary to always use new arch client except `cdc server`
  cmd/cdc/main.go
  cmd/cdc/server/server.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L, release-note-none

#1143 schemastore: fix register partition table
  logservice/schemastore/disk_format.go
  logservice/schemastore/multi_version.go
  logservice/schemastore/multi_version_test_utils.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/persist_storage_test_utils.go
  logservice/schemastore/types.go
Labels: lgtm, approved, size/XL, release-note

#1107 Fix a `PANIC` in coordinator.
  api/v2/coordinator.go
  cmd/cdc/server/server.go
  coordinator/coordinator.go
  coordinator/coordinator_test.go
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
  downstreamadapter/eventcollector/event_collector.go
  pkg/messaging/message_center.go
  pkg/messaging/proto/message.proto
  pkg/messaging/target.go
  pkg/server/coordinator.go
  server/module_election.go
  server/server.go
  tests/integration_tests/_utils/cleanup_process
  tests/integration_tests/_utils/kill_cdc_pid
  tests/integration_tests/_utils/random_kill_process
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/ddl_sequence/run.sh
  tests/integration_tests/fail_over_ddl_A/run.sh
  tests/integration_tests/fail_over_ddl_mix/conf/diff_config.toml
  tests/integration_tests/fail_over_ddl_mix/run.sh
  tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh
  tests/integration_tests/move_table/run.sh
  tests/integration_tests/tiflash/run.sh
Labels: lgtm, approved, size/XL, release-note-none

#1149 workload: add `update` action for sysbench schema
  tools/workload/app.go
  tools/workload/config.go
  tools/workload/dbmanager.go
  tools/workload/main.go
  tools/workload/schema/bank2/bank2.go
  tools/workload/schema/bankupdate/bank_update.go
  tools/workload/schema/crawler/crawler.go
  tools/workload/schema/interface.go
  tools/workload/schema/largerow/large_row.go
  tools/workload/schema/shop/shop.go
  tools/workload/schema/sysbench/readme.md
  tools/workload/schema/sysbench/sysbench.go
  tools/workload/statistics.go
  tools/workload/update.go
Labels: hold, lgtm, approved, size/XXL, release-note-none

#1161 Fix data race in ds
  utils/dynstream/parallel_dynamic_stream.go
Labels: lgtm, approved, release-note, size/XS

#1159 schemastore: add retry when SetServiceGCSafepoint meet error
  logservice/schemastore/persist_storage.go
Labels: lgtm, approved, size/XS, release-note-none

#1172 dispacther: fix a data race
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
  server/server.go
  tests/integration_tests/fail_over/run.sh
  tests/integration_tests/fail_over_ddl_A/run.sh
  tests/integration_tests/fail_over_ddl_B/run.sh
  tests/integration_tests/fail_over_ddl_C/run.sh
  tests/integration_tests/fail_over_ddl_D/run.sh
  tests/integration_tests/fail_over_ddl_E/run.sh
  tests/integration_tests/fail_over_ddl_F/run.sh
  tests/integration_tests/fail_over_ddl_G/run.sh
  tests/integration_tests/fail_over_ddl_H/run.sh
  tests/integration_tests/fail_over_ddl_I/run.sh
  tests/integration_tests/fail_over_ddl_J/run.sh
  tests/integration_tests/fail_over_ddl_K/run.sh
  tests/integration_tests/fail_over_ddl_L/run.sh
  tests/integration_tests/fail_over_ddl_M/run.sh
  tests/integration_tests/fail_over_ddl_N/run.sh
  tests/integration_tests/fail_over_ddl_O/run.sh
  tests/integration_tests/fail_over_ddl_mix/run.sh
  tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh
Labels: lgtm, approved, release-note, size/M

#1178 Fix tidb-only setting for partition ddls
  logservice/schemastore/persist_storage_ddl_handlers.go
Labels: lgtm, approved, release-note, size/XS

#1157 Support to batch sync point event
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatcher/table_progress.go
  pkg/common/event/sync_point_event.go
  pkg/eventservice/event_broker.go
  pkg/sink/mysql/mysql_writer_for_syncpoint.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, release-note, size/L

#1187 *: adjust some code and remove unused code
  downstreamadapter/sink/conflictdetector/helper.go
  downstreamadapter/sink/helper/eventrouter/partition/columns.go
  downstreamadapter/sink/helper/eventrouter/partition/index_value.go
  pkg/common/event/dml_event.go
  pkg/common/event/mounter_test.go
  pkg/common/event/redo.go
  pkg/common/event/row_change.go
  pkg/common/helper.go
  pkg/common/table_info.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/sink/mysql/sql_builder.go
Labels: lgtm, approved, size/L, release-note-none

#1175 metrics: fix gc safe point metrics and adjust some monitoring
  metrics/grafana/ticdc_new_arch.json
  pkg/common/metrics.go
  pkg/metrics/init.go
Labels: lgtm, approved, size/XXL, release-note-none

#1190 codec(ticdc): refactor the canal-json encoder, add canal-json decoder and unit test
  pkg/common/table_info.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/canal/canal_json_txn_decoder.go
  pkg/sink/codec/canal/codec_test.go
  pkg/sink/codec/canal/helper.go
  pkg/sink/codec/common/decoder.go
  pkg/sink/codec/common/helper.go
Labels: lgtm, approved, size/XXL, release-note-none

#1114 *: support BDR Mode
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/eventcollector/event_collector.go
  eventpb/event.pb.go
  eventpb/event.proto
  logservice/eventstore/event_store.go
  logservice/logpuller/region_event_handler_test.go
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/region_state.go
  logservice/logpuller/subscription_client.go
  logservice/logpuller/subscription_client_test.go
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/persist_storage.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  maintainer/barrier_event.go
  pkg/common/event/ddl_event.go
  pkg/config/changefeed.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_service.go
  pkg/eventservice/event_service_test.go
  pkg/messaging/message.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XL, release-note-none

#1176 messaging: fix error
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  pkg/messaging/target.go
  server/module_grpc.go
  utils/conn/helper.go
Labels: lgtm, approved, size/L, release-note-none
