Repository pingcap/ticdc, pull requests merged in 2025-05, with the labels that each got.

#1293 eventBroker: remove scan txn limit
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/eventcollector/helper.go
  logservice/logpuller/subscription_client.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/messaging/remote_target.go
  utils/dynstream/interfaces.go
  utils/dynstream/memory_control.go
  utils/dynstream/memory_control_test.go
Labels: lgtm, approved, size/L, release-note-none

#1297 workaround panic in maintainer
  maintainer/replica/checker.go
Labels: lgtm, approved, release-note, size/XS

#1295 mysql: group multiple dml events by the table id instead of the dispatcher id
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_dml.go
Labels: lgtm, approved, size/M, release-note-none

#1301 update tiflow dependency
  go.mod
  go.sum
Labels: lgtm, approved, release-note, size/XS

#1302 Fix data race in ds
  downstreamadapter/eventcollector/event_collector.go
Labels: lgtm, approved, release-note, size/XS

#1300 test: Add intergration test for random ddl with random table scheduling
  tests/integration_tests/ddl_with_random_move_table/conf/diff_config.toml
  tests/integration_tests/ddl_with_random_move_table/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, release-note, size/L

#1309 log: add some log in remove dispatcher
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
Labels: lgtm, approved, size/S, release-note

#1313 kafka, mysql: refactor the interface and some tiny adjust
  api/v2/changefeed.go
  changefeed.toml
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/sink/eventrouter/event_router.go
  downstreamadapter/sink/eventrouter/partition/generator.go
  downstreamadapter/sink/eventrouter/partition/index_value.go
  downstreamadapter/sink/eventrouter/topic/topic.go
  downstreamadapter/sink/mysql/causality/conflict_detector.go
  downstreamadapter/sink/mysql/causality/txn_cache.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/sink.go
  pkg/common/table_info.go
  pkg/common/table_info_helper.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_helper.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, size/L, release-note-none

#1316 codoc: decoder no need to report error to simplify the caller logic
  pkg/sink/codec/avro/confluent_schema_registry.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/encoder_test.go
  pkg/sink/codec/builder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/canal/canal_json_txn_decoder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/ddl.go
  pkg/sink/codec/common/ddl_test.go
  pkg/sink/codec/common/decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/table_info_cache.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_decoder_test.go
  pkg/sink/codec/debezium/decode.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/open/message.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1308 eventBroker: refactor doScan function
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  logservice/eventstore/event_store.go
  pkg/common/event/mounter.go
  pkg/common/event/util.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_broker_test.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service_test.go
Labels: lgtm, approved, size/XXL, release-note-none

#1324 event: add a DML2UpdateEvent method to assist with testing
  pkg/common/event/util.go
Labels: lgtm, approved, size/M, release-note-none

#1315 txnutil: fix data race in gcManager
  pkg/txnutil/gc/gc_manager.go
Labels: lgtm, approved, size/S, release-note-none

#1003 add more consumer related code
  cmd/kafka-consumer/consumer.go
  cmd/kafka-consumer/event_group.go
  cmd/kafka-consumer/main.go
  cmd/kafka-consumer/option.go
  cmd/kafka-consumer/writer.go
  downstreamadapter/sink/eventrouter/partition/index_value.go
  pkg/common/event/mounter.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/encoder_test.go
  pkg/sink/codec/builder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/debezium/decode.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/mysql/mysql_writer_dml.go
  tests/integration_tests/_utils/run_kafka_consumer
  tests/integration_tests/avro_basic/data/data.sql
  tests/integration_tests/avro_basic/run.sh
  tests/integration_tests/canal_json_claim_check/run.sh
  tests/integration_tests/canal_json_handle_key_only/run.sh
  tests/integration_tests/kafka_column_selector/run.sh
  tests/integration_tests/kafka_simple_basic/run.sh
  tests/integration_tests/kafka_simple_basic_avro/run.sh
  tests/integration_tests/kafka_simple_claim_check/run.sh
  tests/integration_tests/kafka_simple_claim_check_avro/run.sh
  tests/integration_tests/kafka_simple_handle_key_only/run.sh
  tests/integration_tests/kafka_simple_handle_key_only_avro/run.sh
  tests/integration_tests/mq_sink_dispatcher/run.sh
  tests/integration_tests/open_protocol_claim_check/run.sh
  tests/integration_tests/open_protocol_handle_key_only/run.sh
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/XXL, release-note-none

#1318 fix ddl bug and add test for the scenario about failover when writing ddl and dmls on split tables
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  maintainer/barrier.go
  maintainer/barrier_event.go
  maintainer/replica/replication_span.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  tests/integration_tests/ddl_for_split_tables_with_failover/conf/changefeed.toml
  tests/integration_tests/ddl_for_split_tables_with_failover/conf/diff_config.toml
  tests/integration_tests/ddl_for_split_tables_with_failover/data/pre.sql
  tests/integration_tests/ddl_for_split_tables_with_failover/run.sh
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, size/XL, release-note

#1326 mysql: fix duplicate key error
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_dml_test.go
Labels: lgtm, approved, size/XL, release-note-none

#1323 tools: fix crawler workload
  tools/workload/app.go
  tools/workload/schema/crawler/crawler.go
  tools/workload/update.go
Labels: lgtm, approved, size/S, release-note

#1332 codec: fix debezium decoder
  pkg/sink/codec/debezium/decoder.go
  tests/integration_tests/run_light_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1333 codec: fix debezium decoder
  pkg/sink/codec/debezium/decoder.go
Labels: lgtm, approved, size/S, release-note-none

#1331 metric: improve dashboard
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, size/XXL, release-note-none

#1294 event, *: make multiple DMLEvents share one chunk
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/eventcollector/dispatcher_stat.go
  downstreamadapter/eventcollector/event_collector.go
  downstreamadapter/eventcollector/event_collector_test.go
  downstreamadapter/sink/blackhole/sink.go
  downstreamadapter/sink/cloudstorage/dml_writers.go
  downstreamadapter/sink/cloudstorage/dml_writers_test.go
  downstreamadapter/sink/cloudstorage/sink_test.go
  logservice/eventstore/event_store.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_bench_test.go
  pkg/common/event/dml_event_test.go
  pkg/common/event/interface.go
  pkg/common/event/redo.go
  pkg/common/event/util.go
  pkg/common/table_info.go
  pkg/eventservice/dispatcher_stat.go
  pkg/eventservice/event_broker.go
  pkg/eventservice/event_scanner.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service_test.go
  pkg/messaging/message.go
  pkg/messaging/message_center_integration_test.go
  pkg/metrics/event_service.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/verify_checksum.go
  utils/dynstream/memory_control.go
Labels: lgtm, approved, size/XXL, release-note-none

#1336 metrics: correct some metrics and remove useless panel
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/L

#1319 logservice: refactor event store upload logic
  logservice/coordinator/coordinator.go
  logservice/coordinator/coordinator_test.go
  logservice/eventstore/event_store.go
  logservice/eventstore/event_store_test.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/subscription_client.go
  logservice/logpuller/subscription_client_test.go
  logservice/logservicepb/logservice.pb.go
  logservice/logservicepb/logservice.proto
  logservice/schemastore/ddl_job_fetcher.go
  logservice/schemastore/schema_store.go
  pkg/common/kv_entry.go
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, release-note, size/XXL

#1342 codec: fix debezium protocol
  pkg/common/event/ddl_event.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/codec_test.go
  pkg/sink/codec/simple/decoder.go
  tests/integration_tests/run_heavy_it_in_ci.sh
Labels: lgtm, approved, size/M, release-note-none

#1345 metrics: fix typo
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/XS

#1350 dispatcher: remove GetStartTsList from sink interface, instead be a special function of mysql sink
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/sink/blackhole/sink.go
  downstreamadapter/sink/cloudstorage/sink.go
  downstreamadapter/sink/kafka/sink.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  downstreamadapter/sink/pulsar/sink.go
  downstreamadapter/sink/sink.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
Labels: lgtm, approved, release-note, size/L

#1352 dispatcher: reorg the functions in dispatcher to make code clean
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_block_event.go
  downstreamadapter/dispatcher/dispatcher_info.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/event_collector.go
Labels: lgtm, approved, release-note, size/XXL

#1344 *: move spanz to common package
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_block_event.go
  downstreamadapter/dispatcher/dispatcher_info.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/downstream_performance_test.go
  downstreamadapter/eventcollector/event_collector_test.go
  heartbeatpb/table_span.go
  logservice/coordinator/coordinator.go
  logservice/coordinator/coordinator_test.go
  logservice/eventstore/event_store.go
  logservice/logpuller/region_event_handler_test.go
  logservice/logpuller/regionlock/region_range_lock_test.go
  logservice/logpuller/subscription_client.go
  logservice/logservicepb/event_store.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  maintainer/barrier_event.go
  maintainer/barrier_event_test.go
  maintainer/barrier_test.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_controller_test.go
  maintainer/maintainer_manager_test.go
  maintainer/range_checker/table_span_range_checker.go
  maintainer/range_checker/table_span_range_checker_test.go
  maintainer/replica/replication_db_test.go
  maintainer/replica/replication_span.go
  maintainer/scheduler/split.go
  maintainer/split/region_count_splitter_test.go
  maintainer/split/splitter_test.go
  maintainer/split/write_bytes_splitter.go
  pkg/common/event/mounter.go
  pkg/common/span_op.go
  pkg/common/span_test.go
  pkg/common/table_span.go
  pkg/eventservice/event_broker.go
  pkg/pdutil/api_client.go
  pkg/pdutil/api_client_test.go
  pkg/sink/util/helper.go
  pkg/spanz/btree_map.go
  pkg/spanz/btree_map_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
  pkg/spanz/hash_map.go
  pkg/spanz/hash_map_test.go
  pkg/spanz/map_bench_test.go
  pkg/spanz/set.go
  pkg/spanz/set_test.go
  pkg/spanz/span.go
  pkg/spanz/sync_map.go
  redo/common/util_test.go
  redo/doc.go
  redo/manager.go
  redo/manager_test.go
  redo/meta_manager.go
  redo/writer/writer.go
Labels: lgtm, approved, size/XXL, release-note-none

#1347 logpuller: fix the kv client query store id failed caused resolved-ts lag increase
  logservice/logpuller/mock_upstream.go
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/subscription_client.go
  pkg/version/check.go
Labels: lgtm, approved, size/M, release-note-none

#1355 eventDispatcherManager: reorg the event dispatcher dispatcher to make code clean
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager_info.go
Labels: lgtm, approved, size/XL, release-note

#1343 *: optimize checkpointTs lag
  downstreamadapter/eventcollector/helper.go
  logservice/eventstore/event_store.go
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/regionlock/region_range_lock.go
  logservice/logpuller/regionlock/region_range_lock_test.go
  pkg/config/kvclient.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer_dml.go
Labels: lgtm, approved, size/L, release-note-none

#1359 kafka: option should be adjust first and then new the kafka factory
  api/v2/changefeed.go
  downstreamadapter/sink/kafka/helper.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_cluster_admin_client.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/oauth2_token_provider.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
Labels: lgtm, approved, size/L, release-note-none

#1366 metrics: change name to keep consistency with other component
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, release-note, size/XS

#1363 dispatcher: fix bug in prepareDMLs
  pkg/sink/mysql/mysql_writer_dml.go
Labels: lgtm, approved, size/S, release-note

#1364 dispatcher: fix the bug during remove dispatcher
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_dml_test.go
  pkg/sink/mysql/mysql_writer_test.go
Labels: lgtm, approved, release-note, size/L

#1374 sink: improve the performance of mysql sink
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/sink/mysql/causality/conflict_detector.go
  downstreamadapter/sink/mysql/causality/txn_cache.go
  downstreamadapter/sink/mysql/sink.go
  downstreamadapter/sink/mysql/sink_test.go
  maintainer/maintainer.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_test.go
  utils/chann/unlimited_chann.go
Labels: lgtm, approved, release-note, size/L

#1384 sink: set `tidb_cdc_write_source` in dsn instead of set session variable seperately before each txn
  pkg/sink/mysql/config.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer_ddl.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
Labels: lgtm, approved, release-note, size/L

#1372 consumer: support handling partition table
  cmd/kafka-consumer/writer.go
  pkg/common/event/dml_event.go
  pkg/common/event/dml_event_bench_test.go
  pkg/common/event/util.go
  pkg/eventservice/event_scanner_test.go
  pkg/eventservice/event_service_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_test.go
  pkg/sink/codec/common/ddl.go
  pkg/sink/codec/common/table_info_cache.go
  pkg/sink/codec/debezium/decoder.go
  pkg/sink/codec/open/codec.go
  pkg/sink/codec/open/decoder.go
  pkg/sink/codec/open/encoder_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/mysql/mysql_writer_dml.go
  tests/integration_tests/kafka_simple_basic/data/pre_ddl.sql
Labels: lgtm, approved, size/XXL, release-note-none
