Repository pingcap/ticdc, pull requests merged in 2025-01, with the labels that each got.

#901 changefeed: fix data race
  cmd/cdc/server/server.go
  coordinator/changefeed/changefeed.go
  coordinator/changefeed/changefeed_test.go
  coordinator/controller.go
  server/server.go
  tests/integration_tests/http_api_tls/run.sh
  tests/integration_tests/http_api_tls_with_user_auth/run.sh
Labels: lgtm, approved, size/L

#897 sink: support force replicate
  .github/workflows/integration_test_mysql.yaml
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/sink/mysql/sql_builder.go
  pkg/sink/mysql/sql_builder_benchmark_test.go
  pkg/sink/mysql/sql_builder_test.go
  tests/integration_tests/tidb_mysql_test/run.sh
Labels: lgtm, approved, size/M

#904 schemastore: fix table filter
  logservice/schemastore/persist_storage_ddl_handlers.go
Labels: lgtm, approved, size/S, release-note

#895 Adjust ddl logic in maintainer
  .github/workflows/integration_test_mysql.yaml
  coordinator/changefeed/changefeed.go
  coordinator/controller.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  maintainer/barrier.go
  maintainer/barrier_event.go
  maintainer/barrier_event_test.go
  maintainer/barrier_test.go
  maintainer/maintainer_controller.go
  maintainer/range_checker/bool_range_checker.go
  maintainer/range_checker/range_checker.go
  maintainer/range_checker/table_count_range_checker.go
  maintainer/range_checker/table_span_range_checker.go
  maintainer/replica/replication_db.go
  maintainer/replica/replication_db_test.go
  pkg/common/table_info.go
  pkg/eventservice/event_broker.go
  pkg/sink/mysql/mysql_writer_ddl.go
Labels: lgtm, approved, size/XXL

#910 ut, makefile: consolidate unit tests into single makefile target
  .gitignore
  Makefile
Labels: lgtm, approved, size/M, release-note-none

#912 test: fix resolve lock test
  .github/workflows/integration_test_mysql.yaml
  Makefile
  logservice/logpuller/region_event_handler.go
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/subscription_client.go
  logservice/logpuller/subscription_client_test.go
Labels: lgtm, approved, release-note, size/L

#911 Fix the close order of dispatchers
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
Labels: lgtm, approved, release-note, size/XS

#906 api: fix move table API
  .github/workflows/integration_test_mysql.yaml
  api/v2/api.go
  api/v2/changefeed.go
  api/v2/helper.go
  api/v2/model.go
  coordinator/controller.go
  coordinator/controller_test.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_manager.go
  pkg/config/changefeed.go
  server/watcher/module_node_manager.go
  tests/integration_tests/move_table/main.go
Labels: lgtm, approved, size/XXL, release-note-none

#908 monitor: set the y min to 0 for panels
  downstreamadapter/sink/helper/eventrouter/partition/generator.go
  metrics/grafana/ticdc_new_arch.json
Labels: lgtm, approved, size/XXL, release-note-none

#801 support pipelined dml
  logservice/logpuller/txn_matcher.go
  logservice/logpuller/txn_matcher_test.go
Labels: lgtm, approved, size/M, release-note-none

#871 test: add a group test based on 7.5 upstream
  .github/workflows/integration_test_mysql.yaml
Labels: lgtm, approved, size/L, release-note-none

#922 Fix data race in ut
  .github/workflows/integration_test_mysql.yaml
  downstreamadapter/sink/kafka_sink_test.go
  downstreamadapter/sink/mysql_sink_test.go
  logservice/coordinator/coordinator_test.go
  maintainer/maintainer.go
  maintainer/maintainer_test.go
Labels: lgtm, approved, release-note, size/L

#923 schemastore: fix unit test
  logservice/schemastore/persist_storage_ddl_handlers.go
Labels: lgtm, approved, release-note, size/XS

#916 test: fix intetragion test case `changefeed_fast_fail`
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  logservice/schemastore/persist_storage.go
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/changefeed_fast_fail/run.sh
Labels: lgtm, approved, size/M, release-note-none

#926 *: Improve cdc server exit logic
  .github/workflows/integration_test_mysql.yaml
  cmd/cdc/server/server.go
  coordinator/coordinator.go
  coordinator/coordinator_test.go
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatcher/helper.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/heartbeat_collector.go
  downstreamadapter/dispatchermanager/heartbeat_queue.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
  downstreamadapter/eventcollector/event_collector.go
  maintainer/barrier_event_test.go
  maintainer/maintainer_manager.go
  maintainer/maintainer_manager_test.go
  maintainer/maintainer_test.go
  pkg/common/sub_module.go
  pkg/errors/error.go
  pkg/eventservice/event_broker.go
  pkg/messaging/message_center.go
  pkg/pdutil/clock.go
  pkg/pdutil/clock_test.go
  pkg/txnutil/gc/doc.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/metrics.go
  pkg/txnutil/gc/testing.go
  pkg/upstream/upstream.go
  server/module_election.go
  server/server.go
  server/server_prepare.go
  tests/integration_tests/_utils/ensure
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/cli_tls_with_auth/run.sh
  tests/integration_tests/cli_with_auth/run.sh
  utils/dynstream/memory_control.go
  utils/dynstream/parallel_dynamic_stream.go
Labels: lgtm, approved, size/XXL, release-note-none

#931 test: try fix unstable test
  logservice/logpuller/subscription_client_test.go
Labels: lgtm, approved, release-note, size/XS

#924 Fix unstable test `ddl-attribute`
  tests/integration_tests/ddl_attributes/run.sh
Labels: lgtm, approved, release-note, size/M

#930 test: fix integration test `changefeed_error`
  .github/workflows/integration_test_mysql.yaml
  coordinator/coordinator.go
  maintainer/maintainer.go
  maintainer/maintainer_manager.go
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/changefeed_fast_fail/run.sh
Labels: lgtm, approved, size/L, release-note-none

#933 ci: enable lint checks in CI and fix related code issues
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/dispatcher/dispatcher_test.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/sink/helper/eventrouter/partition/generator.go
  maintainer/barrier_event.go
  pkg/common/event/dml_event.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/cli_tls_with_auth/run.sh
Labels: lgtm, approved, size/M, release-note-none

#934 schemastore: support schema charset
  logservice/schemastore/persist_storage_ddl_handlers.go
Labels: lgtm, approved, release-note, size/M

#929 Not sync ineligable table when not enable force replicate
  api/v2/changefeed.go
  downstreamadapter/dispatchermanager/event_dispatcher_manager.go
  downstreamadapter/dispatchermanager/helper.go
  downstreamadapter/eventcollector/event_collector.go
  eventpb/event.pb.go
  eventpb/event.proto
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test_utils.go
  maintainer/maintainer_controller.go
  pkg/config/changefeed.go
  pkg/eventservice/event_service_test.go
  pkg/filter/filter.go
  utils/dynstream/interfaces.go
Labels: lgtm, approved, release-note, size/XXL

#936 Enable integration test `cdc`
  .github/workflows/integration_test_mysql.yaml
Labels: lgtm, approved, release-note, size/XS

#940 github: add issue template
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/ISSUE_TEMPLATE/ticdc-bug-report.yml
Labels: lgtm, approved, size/L, release-note-none

#938 coordinator: fix a bug that keep changefeed in warning state
  coordinator/changefeed/backoff.go
  coordinator/changefeed/changefeed.go
  coordinator/changefeed/changefeed_db.go
  coordinator/controller.go
  coordinator/coordinator_test.go
  heartbeatpb/heartbeat.pb.go
  logservice/schemastore/persist_storage_ddl_handlers.go
  maintainer/maintainer.go
  maintainer/maintainer_manager.go
  pkg/bootstrap/bootstrap.go
  pkg/common/format.go
  pkg/common/format_test.go
  pkg/messaging/message_center.go
  tests/integration_tests/ddl_attributes/run.sh
Labels: lgtm, approved, size/XXL, release-note-none

#943 *: fix several integration test cases
  .github/workflows/integration_test_mysql.yaml
  maintainer/replica/replication_span.go
  pkg/errors/error.go
  pkg/retry/options.go
  pkg/retry/retry_test.go
  pkg/sink/mysql/helper.go
  pkg/sink/mysql/mysql_writer_dml.go
  tests/integration_tests/changefeed_auto_stop/conf/diff_config.toml
  tests/integration_tests/changefeed_auto_stop/conf/workload
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_dup_error_restart/run.sh
  tests/integration_tests/mysql_sink_retry/conf/diff_config.toml
  tests/integration_tests/mysql_sink_retry/conf/workload
  tests/integration_tests/mysql_sink_retry/run.sh
  tests/integration_tests/sink_hang/conf/diff_config.toml
  tests/integration_tests/sink_hang/run.sh
Labels: lgtm, approved, size/XL, release-note-none

#948 test: fix schemastore unit tests
  logservice/schemastore/disk_format.go
  logservice/schemastore/persist_storage_test.go
  logservice/schemastore/persist_storage_test_utils.go
  tests/integration_tests/mysql_sink_retry/run.sh
Labels: lgtm, approved, release-note, size/L

#946 ci: remove UT and linux build CI from gitHub actions
  .github/workflows/check_and_build.yaml
  .github/workflows/uint_test.yaml
Labels: lgtm, approved, size/L, release-note-none

#844 sink: replace Kafka client with confluent-kafka-go
  Makefile
  downstreamadapter/sink/helper/topicmanager/kafka_topic_manager_test.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/worker/helper.go
  downstreamadapter/worker/kafka_ddl_worker_test.go
  downstreamadapter/worker/kafka_dml_worker_test.go
  downstreamadapter/worker/producer/kafka_ddl_producer_test.go
  downstreamadapter/worker/producer/kafka_dml_producer_test.go
  go.mod
  pkg/leakutil/leak_helper.go
  pkg/logger/log.go
  pkg/sink/codec/common/message.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/config.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/kafka.go
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_cluster_admin_client.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/oauth2_token_provider.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/client.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/gssapi.go
  pkg/sink/kafka/v2/manual_balancer.go
  pkg/sink/kafka/v2/metrics_collector.go
  pkg/sink/kafka/v2/writer.go
  tests/integration_tests/kafka_compression/run.sh
  tests/integration_tests/open_protocol_claim_check/run.sh
Labels: lgtm, approved, size/XXL

#945 Fix decode chunk
  pkg/common/event/chunk.go
Labels: lgtm, approved, release-note, size/XS

#950 test: fix `gc_safepoint`
  api/v2/changefeed.go
  coordinator/changefeed/changefeed.go
  coordinator/controller.go
  coordinator/coordinator.go
  heartbeatpb/heartbeat.pb.go
  heartbeatpb/heartbeat.proto
  logservice/schemastore/persist_storage.go
  logservice/schemastore/schema_store.go
  maintainer/maintainer.go
  maintainer/maintainer_controller.go
  maintainer/maintainer_manager.go
  maintainer/maintainer_manager_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_service.go
  server/module_election.go
  tests/integration_tests/gc_safepoint/run.sh
Labels: lgtm, approved, size/XL, release-note-none

#949 test: enable multi_tables_ddl test
  .github/workflows/integration_test_mysql.yaml
  logservice/schemastore/persist_storage_ddl_handlers.go
  logservice/schemastore/persist_storage_test.go
  pkg/common/event/ddl_event.go
  tests/integration_tests/multi_tables_ddl/run.sh
Labels: lgtm, approved, release-note, size/L

#952 test: fix integration test `capture_suicide_while_balance_table`
  .github/workflows/integration_test_mysql.yaml
  logservice/logpuller/region_request_worker.go
  logservice/logpuller/subscription_client.go
  maintainer/maintainer_controller.go
  pkg/sink/mysql/mysql_writer_dml.go
  pkg/util/atomic.go
  pkg/util/atomic_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
  tests/integration_tests/kv_client_stream_reconnect/run.sh
  tests/integration_tests/owner_remove_table_error/conf/diff_config.toml
  tests/integration_tests/owner_remove_table_error/run.sh
Labels: lgtm, approved, size/XL, release-note-none

#954 *: fix cdc compile failed
  Makefile
  downstreamadapter/sink/helper/topicmanager/kafka_topic_manager_test.go
  downstreamadapter/sink/kafka_sink.go
  downstreamadapter/worker/helper.go
  downstreamadapter/worker/kafka_ddl_worker_test.go
  downstreamadapter/worker/kafka_dml_worker_test.go
  downstreamadapter/worker/producer/kafka_ddl_producer_test.go
  downstreamadapter/worker/producer/kafka_dml_producer_test.go
  go.mod
  pkg/leakutil/leak_helper.go
  pkg/logger/log.go
  pkg/sink/codec/common/message.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/config.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/kafka.go
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_cluster_admin_client.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/oauth2_token_provider.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/client.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/gssapi.go
  pkg/sink/kafka/v2/manual_balancer.go
  pkg/sink/kafka/v2/metrics_collector.go
  pkg/sink/kafka/v2/writer.go
  tests/integration_tests/kafka_compression/run.sh
  tests/integration_tests/open_protocol_claim_check/run.sh
Labels: lgtm, approved, release-note, size/XXL

#955 *: fix schema store log
  logservice/schemastore/multi_version.go
  logservice/schemastore/multi_version_test.go
Labels: lgtm, approved, release-note, size/M

#951 Use ddl_ts to fix the atomic problem of ddl_ts and ddl event; Add a mix failover test for test ddl failover cases randomly
  .github/workflows/integration_test_mysql.yaml
  downstreamadapter/dispatcher/dispatcher.go
  downstreamadapter/sink/mysql_sink_test.go
  maintainer/barrier.go
  maintainer/barrier_event.go
  maintainer/barrier_event_test.go
  pkg/sink/mysql/mysql_writer.go
  pkg/sink/mysql/mysql_writer_for_ddl_ts.go
  pkg/sink/mysql/mysql_writer_for_syncpoint.go
  pkg/sink/mysql/mysql_writer_test.go
  tests/integration_tests/_utils/run_sql_ignore_error
  tests/integration_tests/fail_over_ddl_mix/conf/diff_config.toml
  tests/integration_tests/fail_over_ddl_mix/run.sh
Labels: lgtm, approved, release-note, size/XXL

#957 Fix data race in coordinator
  coordinator/controller.go
Labels: lgtm, approved, size/S, release-note
